# SPDX-License-Identifier: MIT
"""The deployment settings file androiddeployqt reads.

``androiddeployqt`` is driven by a JSON file that Qt's CMake writes. Without
it no Android package can be built, however well the compile and link went.

    from pcons.toolchains.qt.android import android_deployment_settings

    env.apply_cross_preset(android(ndk=NDK, api=35, sdk=SDK))
    app = project.QtSharedLibrary("myapp", env, sources=[...])
    settings = android_deployment_settings(project, env, app=app)

This writes one ABI and one application. Two things it deliberately does
not answer, because androiddeployqt answers them itself and a pcons key
would only be a second opinion:

- the transitive Qt library set, which it reads out of the staged ``.so``
  with ``llvm-readobj --needed-libs`` and out of Qt's own
  ``Qt6X_<abi>-android-dependencies.xml``
- the QML imports, which it finds by running ``qmlimportscanner``

``android-deploy-plugins`` is left out for the same reason. Absent, Qt's
XML decides which plugin directories are bundled: a larger package, never a
broken one.
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING, Any

from pcons.toolchains.presets import CrossPreset

if TYPE_CHECKING:
    from pcons.core.environment import Environment
    from pcons.core.project import Project
    from pcons.core.target import Target

#: androiddeployqt reads this file and nothing else does, so the text only has
#: to say who wrote it. Qt's CMake writes the same sentence about itself.
_DESCRIPTION = (
    "This file is generated by pcons to be read by androiddeployqt "
    "and should not be modified by hand."
)

#: Where each part of a Qt for Android install sits under its prefix. Read off
#: Qt 6.11.1; keyed by ABI in the file, like ``qt`` itself, because a
#: multi-ABI package may name a different prefix per ABI.
_QT_SUBDIRECTORIES: dict[str, str] = {
    "qtDataDirectory": ".",
    "qtLibExecsDirectory": "libexec",
    "qtLibsDirectory": "lib",
    "qtPluginsDirectory": "plugins",
    "qtQmlDirectory": "qml",
}

#: Tools androiddeployqt runs itself, and the key each goes under. They are
#: host programs: a Qt for Android install ships no runnable moc or rcc, and
#: ``QtPackage`` already answers with the host directories for one (its
#: ``qtpaths --query`` reports QT_HOST_BINS and QT_HOST_LIBEXECS). Omitted
#: rather than demanded when a build has none, since a missing optional tool
#: must not make the whole file unwritable.
_HOST_TOOLS: dict[str, str] = {
    "rcc-binary": "rcc",
    "qml-importscanner-binary": "qmlimportscanner",
    "qml-dom-binary": "qmldom",
}

#: The NDK sysroot directory each Android ABI's libraries live in. Not the
#: compiler triple: that carries the API level ("aarch64-linux-android35"),
#: and for armeabi-v7a the two disagree on the CPU as well ("armv7a-" against
#: "arm-"). Read off <ndk>/toolchains/llvm/prebuilt/<host>/sysroot/usr/lib.
_SYSROOT_DIR: dict[str, str] = {
    "arm64-v8a": "aarch64-linux-android",
    "armeabi-v7a": "arm-linux-androideabi",
    "x86_64": "x86_64-linux-android",
    "x86": "i686-linux-android",
}


def application_binary(app: Target | str) -> str:
    """The name androiddeployqt knows the application by.

    It builds ``lib<name>_<abi>.so`` out of this and looks for that file
    under its output directory, so it is a name and never a path.

    Args:
        app: The application target, or its name.

    Returns:
        The name.
    """
    return app if isinstance(app, str) else app.name


def application_library_name(app: Target | str, abi: str) -> str:
    """The file name androiddeployqt reads the application out of.

    The ABI suffix is not decoration. Measured against Qt 6.11.1: with the
    file staged under its plain name androiddeployqt logs an ``llvm-readobj:
    No such file or directory`` for the suffixed one, packages nothing, and
    still exits 0.

    Args:
        app: The application target, or its name.
        abi: The Android ABI ("arm64-v8a").

    Returns:
        The file name, ``lib<name>_<abi>.so``.
    """
    return f"lib{application_binary(app)}_{abi}.so"


def android_output_dir(env: Environment, app: Target | str) -> Path:
    """The directory androiddeployqt fills for this application.

    Below the environment's build directory and named after the application,
    because androiddeployqt owns the whole directory and names the package
    it builds after it. Two applications built in one environment therefore
    cannot share one.

    Args:
        env: The environment the application is built in.
        app: The application target, or its name.

    Returns:
        The directory, relative to the project root unless the environment's
        build directory is absolute.
    """
    return env.build_dir_for(Path()) / application_binary(app)


def _library_dir(project: Project, env: Environment) -> Path:
    """Absolute directory this environment writes shared libraries into.

    androiddeployqt reads the paths in the file directly, from wherever it
    runs, so they are absolute. Asked of the same two methods the resolver
    places a shared library with, so the two cannot drift apart.
    """
    directory = env.build_dir_for(Path())
    below = env.output_directory_for("shared_library")
    if below:
        directory = directory / below
    return _absolute(project, directory)


def _android_preset(env: Environment) -> CrossPreset:
    cross = env.cross
    if cross is None or getattr(cross, "ndk", None) is None:
        raise ValueError(
            "androiddeployqt settings need an environment retargeted with "
            "an Android preset: env.apply_cross_preset(android(ndk=..., "
            "api=...))."
        )
    if cross.sdk is None:
        raise ValueError(
            f"androiddeployqt needs the Android SDK and preset "
            f"'{cross.name}' has none. Pass it where the NDK is passed: "
            f"android(ndk=..., api=..., sdk=...)."
        )
    if cross.arch not in _SYSROOT_DIR:
        raise ValueError(
            f"No NDK sysroot directory known for Android ABI "
            f"'{cross.arch}'. Supported: {', '.join(_SYSROOT_DIR)}."
        )
    return cross


def deployment_settings(
    project: Project, env: Environment, *, app: Target | str
) -> dict:
    """The settings androiddeployqt reads, as a dict.

    Every value comes from what the environment was retargeted with or from
    the Qt installation found for it; nothing here searches for anything.
    Use :func:`android_deployment_settings` to write it, unless you mean to
    add keys of your own first.

    Args:
        project: The project.
        env: The environment the application is built in, retargeted with
             an Android preset carrying an ``sdk``.
        app: The application target, or its name. androiddeployqt looks for
             ``lib<name>_<abi>.so`` under the output directory, so this is
             the name and not a path.

    Returns:
        The settings, ready for :func:`json.dump`.

    Raises:
        ValueError: If the environment is not an Android cross environment,
            its preset carries no SDK, or its ABI has no known NDK sysroot
            directory.
        QtNotFoundError: If no Qt installation was found for *env*.
    """
    from pcons.toolchains.qt.finder import QtNotFoundError, qt_install

    cross = _android_preset(env)
    abi = cross.arch

    qt = qt_install(project, env)
    if qt is None:
        raise QtNotFoundError(
            "androiddeployqt settings name the Qt built for the target. "
            "Call find_qt() on this environment first."
        )

    assert cross.ndk is not None and cross.ndk_host is not None
    ndk = Path(cross.ndk)
    host = cross.ndk_host
    stdcpp = ndk / "toolchains" / "llvm" / "prebuilt" / host / "sysroot" / "usr" / "lib"

    settings: dict[str, Any] = {
        "description": _DESCRIPTION,
        "qt": {abi: str(qt.prefix)},
        "extraPrefixDirs": [str(qt.prefix)],
        "extraLibraryDirs": [str(_library_dir(project, env))],
        "sdk": str(cross.sdk),
        "ndk": str(ndk),
        "ndk-host": host,
        "toolchain-prefix": "llvm",
        "tool-prefix": "llvm",
        "toolchain-version": "clang",
        "useLLVM": True,
        "stdcpp-path": f"{stdcpp.as_posix()}/",
        "abi": abi,
        "architectures": {abi: _SYSROOT_DIR[abi]},
        "application-binary": application_binary(app),
        "android-legacy-packaging": False,
        "zstdCompression": False,
        "generate-java-qtquickview-contents": False,
    }
    for key, value in _QT_SUBDIRECTORIES.items():
        settings[key] = {abi: value}
    for key, tool in _HOST_TOOLS.items():
        path = qt.tool_path(tool)
        if path is not None:
            settings[key] = str(path)
    settings.update(_qml_keys(project, env))
    return settings


def _qml_keys(project: Project, env: Environment) -> dict[str, Any]:
    """Where androiddeployqt should point qmlimportscanner, or not to run it.

    The scanner reads the filesystem, so it is given the QML *source*
    directories of this environment's QML modules. Their generated ``qmldir``
    is embedded in a resource and pcons writes it flat, so an import path
    resolves none of the application's own modules -- measured against Qt
    6.11.1 not to matter, as long as every module's source directory is a
    root path: the Qt modules reported are then identical either way.
    """
    from pcons.toolchains.qt.qml import qml_source_dirs

    roots = [
        _absolute(project, directory) for directory in qml_source_dirs(project, env)
    ]
    if not roots:
        return {"qml-skip-import-scanning": True}
    import_paths = [_absolute(project, env.build_dir_for(Path()))]
    return {
        "qml-root-path": [str(root) for root in roots],
        "qml-import-paths": ",".join(str(path) for path in import_paths),
    }


def _absolute(project: Project, directory: Path) -> Path:
    if directory.is_absolute():
        return directory
    return Path(project.root_dir) / directory


def android_deployment_settings(
    project: Project,
    env: Environment,
    *,
    app: Target | str,
    output: str | Path | None = None,
    package_name: str | None = None,
    package_source_dir: str | Path | None = None,
    permissions: Sequence[str] = (),
    build_tools: str | None = None,
) -> Path:
    """Write the deployment settings file and return where it was written.

    Written at configure time, like every other file whose content is
    decided by the build script rather than by running something: see
    :func:`pcons.configure.config_file.configure_file`. Editing the build
    script re-runs pcons, which rewrites this.

    Args:
        project: The project.
        env: The environment the application is built in.
        app: The application target, or its name.
        output: Where to write it. Default:
                ``<build_dir>/android-deployment-settings.json``.
        package_name: The Android package name ("org.example.myapp"). Left
                      out, androiddeployqt takes it from the manifest.
        package_source_dir: A directory of Android sources -- the manifest,
                      Java, resources -- overlaid on Qt's own templates.
                      Made absolute against the project root, since
                      androiddeployqt reads it directly. Building that
                      directory is the caller's: ``project.Install()`` is
                      one way.
        permissions: Android permissions ("android.permission.INTERNET"),
                      as bare names. The ``[{"name": ...}]`` shape the file
                      wants is this function's business, not the caller's.
        build_tools: SDK build-tools revision ("37.0.0"). Left out,
                     androiddeployqt picks the highest installed.

    Returns:
        The path written.
    """
    settings = deployment_settings(project, env, app=app)
    if package_name is not None:
        settings["android-package-name"] = package_name
    if package_source_dir is not None:
        directory = Path(package_source_dir)
        if not directory.is_absolute():
            directory = Path(project.root_dir) / directory
        settings["android-package-source-directory"] = str(directory)
    if permissions:
        settings["permissions"] = [{"name": name} for name in permissions]
    if build_tools is not None:
        settings["sdkBuildToolsRevision"] = build_tools

    if output is None:
        output = (
            Path(env.get("build_dir", "build")) / "android-deployment-settings.json"
        )
    output = Path(output)
    if not output.is_absolute():
        output = Path(project.root_dir) / output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(settings, indent=3) + "\n", encoding="utf-8")
    return output
