# SPDX-License-Identifier: MIT
"""The deployment settings file androiddeployqt reads.

``androiddeployqt`` is driven by a JSON file that Qt's CMake writes. Without
it no Android package can be built, however well the compile and link went.

    from pcons.toolchains.qt.android import android_deployment_settings

    env.apply_cross_preset(android(ndk=NDK, api=35, sdk=SDK))
    app = project.QtSharedLibrary("myapp", env, sources=[...])
    settings = android_deployment_settings(project, env, app=app)

One application, and one ABI unless a mapping of ABI to environment is
passed instead of an environment:

    settings = android_deployment_settings(
        project,
        {"arm64-v8a": arm64_env, "x86_64": x86_64_env},
        primary="arm64-v8a",
        app=app,
    )

Two things it deliberately does not answer, because androiddeployqt
answers them itself and a pcons key would only be a second opinion:

- the transitive Qt library set, which it reads out of the staged ``.so``
  with ``llvm-readobj --needed-libs`` and out of Qt's own
  ``Qt6X_<abi>-android-dependencies.xml``
- the QML imports, which it finds by running ``qmlimportscanner``

``android-deploy-plugins`` is left out for the same reason. Absent, Qt's
XML decides which plugin directories are bundled: a larger package, never a
broken one.
"""

from __future__ import annotations

import json
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path
from typing import TYPE_CHECKING, Any

from pcons.toolchains.presets import CrossPreset

if TYPE_CHECKING:
    from pcons.core.environment import Environment
    from pcons.core.project import Project
    from pcons.core.target import Target

#: androiddeployqt reads this file and nothing else does, so the text only has
#: to say who wrote it. Qt's CMake writes the same sentence about itself.
_DESCRIPTION = (
    "This file is generated by pcons to be read by androiddeployqt "
    "and should not be modified by hand."
)

#: Where each part of a Qt for Android install sits under its prefix. Read off
#: Qt 6.11.1. Keyed by ABI in the file, like ``qt`` and ``architectures``: a
#: multi-ABI settings file written by Qt's own CMake carries all seven as maps
#: with one entry per ABI, even though these five values never vary.
_QT_SUBDIRECTORIES: dict[str, str] = {
    "qtDataDirectory": ".",
    "qtLibExecsDirectory": "libexec",
    "qtLibsDirectory": "lib",
    "qtPluginsDirectory": "plugins",
    "qtQmlDirectory": "qml",
}

#: Tools androiddeployqt runs itself, and the key each goes under. They are
#: host programs: a Qt for Android install ships no runnable moc or rcc, and
#: ``QtPackage`` already answers with the host directories for one (its
#: ``qtpaths --query`` reports QT_HOST_BINS and QT_HOST_LIBEXECS). Omitted
#: rather than demanded when a build has none, since a missing optional tool
#: must not make the whole file unwritable.
_HOST_TOOLS: dict[str, str] = {
    "rcc-binary": "rcc",
    "qml-importscanner-binary": "qmlimportscanner",
    "qml-dom-binary": "qmldom",
}

#: The NDK sysroot directory each Android ABI's libraries live in. Not the
#: compiler triple: that carries the API level ("aarch64-linux-android35"),
#: and for armeabi-v7a the two disagree on the CPU as well ("armv7a-" against
#: "arm-"). Read off <ndk>/toolchains/llvm/prebuilt/<host>/sysroot/usr/lib.
_SYSROOT_DIR: dict[str, str] = {
    "arm64-v8a": "aarch64-linux-android",
    "armeabi-v7a": "arm-linux-androideabi",
    "x86_64": "x86_64-linux-android",
    "x86": "i686-linux-android",
}


def application_binary(app: Target | str) -> str:
    """The name androiddeployqt knows the application by.

    It builds ``lib<name>_<abi>.so`` out of this and looks for that file
    under its output directory, so it is a name and never a path.

    Args:
        app: The application target, or its name.

    Returns:
        The name.
    """
    return app if isinstance(app, str) else app.name


def application_library_name(app: Target | str, abi: str) -> str:
    """The file name androiddeployqt reads the application out of.

    The ABI suffix is not decoration. Measured against Qt 6.11.1: with the
    file staged under its plain name androiddeployqt logs an ``llvm-readobj:
    No such file or directory`` for the suffixed one, packages nothing, and
    still exits 0.

    Args:
        app: The application target, or its name.
        abi: The Android ABI ("arm64-v8a").

    Returns:
        The file name, ``lib<name>_<abi>.so``.
    """
    return f"lib{application_binary(app)}_{abi}.so"


def android_output_dir(env: Environment, app: Target | str) -> Path:
    """The directory androiddeployqt fills for this application.

    Below the environment's build directory and named after the application,
    because androiddeployqt owns the whole directory and names the package
    it builds after it. Two applications built in one environment therefore
    cannot share one.

    Args:
        env: The environment the application is built in.
        app: The application target, or its name.

    Returns:
        The directory, relative to the project root unless the environment's
        build directory is absolute.
    """
    return env.build_dir_for(Path()) / application_binary(app)


def _library_dirs(project: Project, envs: Iterable[Environment]) -> list[Path]:
    """Absolute directories these environments' shared libraries land in.

    androiddeployqt copies the application's own dependencies out of these,
    so one that holds no library gives an APK that dies on its first dlopen,
    having built and installed without complaint.

    One key, every environment: a package over several ABIs builds each
    ABI's libraries somewhere of its own, and naming one ABI's directories
    leaves the others' dependencies out with nothing said about it. Paths
    are absolute because androiddeployqt reads them from wherever it runs.
    """
    found: dict[Path, None] = {}
    for env in envs:
        for directory in _one_environment_library_dirs(project, env):
            found[directory] = None
    return list(found)


def _one_environment_library_dirs(project: Project, env: Environment) -> list[Path]:
    """Where *env*'s shared libraries land.

    One directory per environment is only right for a project whose targets
    all sit in one source directory: a target places itself with its own
    build directory, which carries the subdirectory it was declared in. So
    this asks each shared library where it goes rather than asking the
    environment once.
    """
    below = env.output_directory_for("shared_library")

    def placed(directory: Path) -> Path:
        return _absolute(project, directory / below if below else directory)

    found = {
        placed(target.build_dir): None
        for target in project.targets
        if target._env is env and target.target_type == "shared_library"
    }
    if not found:
        return [placed(env.build_dir_for(Path()))]
    return list(found)


def _android_preset(env: Environment) -> CrossPreset:
    cross = env.cross
    if cross is None or getattr(cross, "ndk", None) is None:
        raise ValueError(
            "androiddeployqt settings need an environment retargeted with "
            "an Android preset: env.apply_cross_preset(android(ndk=..., "
            "api=...))."
        )
    if cross.sdk is None:
        raise ValueError(
            f"androiddeployqt needs the Android SDK and preset "
            f"'{cross.name}' has none. Pass it where the NDK is passed: "
            f"android(ndk=..., api=..., sdk=...)."
        )
    if cross.arch not in _SYSROOT_DIR:
        raise ValueError(
            f"No NDK sysroot directory known for Android ABI "
            f"'{cross.arch}'. Supported: {', '.join(_SYSROOT_DIR)}."
        )
    return cross


def _abi_environments(
    env: Environment | Mapping[str, Environment], primary: str | None
) -> tuple[dict[str, tuple[Environment, CrossPreset]], str]:
    """The environments this package is built from, keyed by ABI.

    A mapping rather than a sequence, because a mapping cannot disagree
    with itself about which ABI an environment is for; the key is checked
    against the preset all the same, since it is the caller who wrote it.

    *primary* is asked for rather than taken as the first key: ``abi``,
    ``extraPrefixDirs`` and the host tool paths all read from it, and
    reordering a dict must not repoint them.
    """
    if not isinstance(env, Mapping):
        cross = _android_preset(env)
        entries = {cross.arch: (env, cross)}
    elif not env:
        raise ValueError(
            "androiddeployqt settings need at least one environment. Pass "
            "the environment itself, or {'arm64-v8a': env, ...}."
        )
    else:
        entries = {abi: (one, _android_preset(one)) for abi, one in env.items()}
        for abi, (_, cross) in entries.items():
            if cross.arch != abi:
                raise ValueError(
                    f"The environment keyed '{abi}' is retargeted for "
                    f"'{cross.arch}'. The key is the ABI its Android preset "
                    f"names, and androiddeployqt reads both."
                )

    if primary is not None:
        if primary not in entries:
            raise ValueError(
                f"primary='{primary}' is not one of the ABIs given: "
                f"{', '.join(entries)}."
            )
        return entries, primary
    if len(entries) > 1:
        raise ValueError(
            f"A package over several ABIs names its primary one: "
            f"primary='...', one of {', '.join(entries)}. The 'abi' key, "
            f"'extraPrefixDirs' and the host tool paths all come from it, so "
            f"it is asked for rather than read off the first entry."
        )
    return entries, next(iter(entries))


def _one_ndk_and_sdk(
    entries: Mapping[str, tuple[Environment, CrossPreset]], primary: str
) -> None:
    """Refuse presets that disagree on what a settings file states once."""
    _, first = entries[primary]
    for abi, (_, cross) in entries.items():
        for key, mine, theirs in (
            ("ndk", first.ndk, cross.ndk),
            ("sdk", first.sdk, cross.sdk),
        ):
            if mine != theirs:
                raise ValueError(
                    f"One settings file states one '{key}', and the presets "
                    f"disagree: '{primary}' names {mine}, '{abi}' names "
                    f"{theirs}."
                )


def deployment_settings(
    project: Project,
    env: Environment | Mapping[str, Environment],
    *,
    app: Target | str,
    primary: str | None = None,
) -> dict:
    """The settings androiddeployqt reads, as a dict.

    Every value comes from what the environments were retargeted with or
    from the Qt installation found for each; nothing here searches for
    anything. Use :func:`android_deployment_settings` to write it, unless
    you mean to add keys of your own first.

    Seven keys are maps of ABI to value -- ``qt``, ``architectures`` and the
    five ``qt*Directory`` ones -- and the rest are written once. ``abi``,
    ``extraPrefixDirs`` and the host tool paths come from *primary* alone;
    measured against a multi-ABI file Qt's own CMake wrote at 6.11.1, where
    none of the three gains a second ABI's entry.

    Args:
        project: The project.
        env: The environment the application is built in, retargeted with
             an Android preset carrying an ``sdk``. For a package over
             several ABIs, a mapping of ABI to environment: each key is the
             ABI its environment's preset names.
        app: The application target, or its name. androiddeployqt looks for
             ``lib<name>_<abi>.so`` under the output directory, so this is
             the name and not a path. One name whatever the ABI count:
             androiddeployqt adds the suffix itself.
        primary: The ABI ``abi`` names, and whose Qt ``extraPrefixDirs``
                 and the host tools come from. Required once *env* names
                 more than one ABI, and never read off the first key.

    Returns:
        The settings, ready for :func:`json.dump`.

    Raises:
        ValueError: If an environment is not an Android cross environment,
            its preset carries no SDK, its ABI has no known NDK sysroot
            directory, a mapping key disagrees with its preset, the presets
            disagree on the NDK or the SDK, or *primary* is missing or names
            an ABI that was not given.
        QtNotFoundError: If no Qt installation was found for an environment.
    """
    from pcons.toolchains.qt.finder import QtNotFoundError, qt_install

    entries, abi = _abi_environments(env, primary)
    _one_ndk_and_sdk(entries, abi)
    cross = entries[abi][1]

    prefixes: dict[str, str] = {}
    for one_abi, (one_env, _) in entries.items():
        qt = qt_install(project, one_env)
        if qt is None:
            raise QtNotFoundError(
                f"androiddeployqt settings name the Qt built for the target, "
                f"and the '{one_abi}' environment has none. Call find_qt() on "
                f"every environment the package is built from."
            )
        prefixes[one_abi] = str(qt.prefix)
        if one_abi == abi:
            primary_qt = qt

    assert cross.ndk is not None and cross.ndk_host is not None
    ndk = Path(cross.ndk)
    host = cross.ndk_host
    stdcpp = ndk / "toolchains" / "llvm" / "prebuilt" / host / "sysroot" / "usr" / "lib"
    environments = [one for one, _ in entries.values()]

    settings: dict[str, Any] = {
        "description": _DESCRIPTION,
        "qt": prefixes,
        "extraPrefixDirs": [prefixes[abi]],
        "extraLibraryDirs": [str(d) for d in _library_dirs(project, environments)],
        "sdk": str(cross.sdk),
        "ndk": str(ndk),
        "ndk-host": host,
        "toolchain-prefix": "llvm",
        "tool-prefix": "llvm",
        "toolchain-version": "clang",
        "useLLVM": True,
        "stdcpp-path": f"{stdcpp.as_posix()}/",
        "abi": abi,
        "architectures": {one: _SYSROOT_DIR[one] for one in entries},
        "application-binary": application_binary(app),
        "android-legacy-packaging": False,
        "zstdCompression": False,
        "generate-java-qtquickview-contents": False,
    }
    for key, value in _QT_SUBDIRECTORIES.items():
        settings[key] = dict.fromkeys(entries, value)
    for key, tool in _HOST_TOOLS.items():
        path = primary_qt.tool_path(tool)
        if path is not None:
            settings[key] = str(path)
    settings.update(_qml_keys(project, environments))
    return settings


def _qml_keys(project: Project, envs: Iterable[Environment]) -> dict[str, Any]:
    """Where androiddeployqt should point qmlimportscanner, or not to run it.

    The scanner reads the filesystem, so it is given the QML *source*
    directories of these environments' QML modules. Their generated
    ``qmldir`` is embedded in a resource and pcons writes it flat, so an
    import path resolves none of the application's own modules -- measured
    against Qt 6.11.1 not to matter, as long as every module's source
    directory is a root path: the Qt modules reported are then identical
    either way.

    One scan serves the whole package, so both keys are the union over
    every ABI's environment. The QML sources of two ABIs are usually the
    same directory and collapse to one entry; their build directories are
    not, and both are named.
    """
    from pcons.toolchains.qt.qml import qml_source_dirs

    roots: dict[str, None] = {}
    import_paths: dict[str, None] = {}
    for env in envs:
        for directory in qml_source_dirs(project, env):
            roots[str(_absolute(project, directory))] = None
        import_paths[str(_absolute(project, env.build_dir_for(Path())))] = None
    if not roots:
        return {"qml-skip-import-scanning": True}
    return {
        "qml-root-path": list(roots),
        "qml-import-paths": ",".join(import_paths),
    }


def _absolute(project: Project, directory: Path) -> Path:
    if directory.is_absolute():
        return directory
    return Path(project.root_dir) / directory


def android_deployment_settings(
    project: Project,
    env: Environment | Mapping[str, Environment],
    *,
    app: Target | str,
    primary: str | None = None,
    output: str | Path | None = None,
    package_name: str | None = None,
    package_source_dir: str | Path | None = None,
    permissions: Sequence[str] = (),
    build_tools: str | None = None,
) -> Path:
    """Write the deployment settings file and return where it was written.

    Written at configure time, like every other file whose content is
    decided by the build script rather than by running something: see
    :func:`pcons.configure.config_file.configure_file`. Editing the build
    script re-runs pcons, which rewrites this.

    Args:
        project: The project.
        env: The environment the application is built in, or a mapping of
             ABI to environment for a package over several ABIs.
        app: The application target, or its name.
        primary: The ABI ``abi``, ``extraPrefixDirs`` and the host tools
                 come from. Required once *env* names more than one.
        output: Where to write it. Default:
                ``<build_dir>/android-deployment-settings.json``.
        package_name: The Android package name ("org.example.myapp"). Left
                      out, androiddeployqt takes it from the manifest.
        package_source_dir: A directory of Android sources -- the manifest,
                      Java, resources -- overlaid on Qt's own templates.
                      Made absolute against the project root, since
                      androiddeployqt reads it directly. Building that
                      directory is the caller's: ``project.Install()`` is
                      one way.
        permissions: Android permissions ("android.permission.INTERNET"),
                      as bare names. The ``[{"name": ...}]`` shape the file
                      wants is this function's business, not the caller's.
        build_tools: SDK build-tools revision ("37.0.0"). Needed for a real
                     package: androiddeployqt does not detect one, and left
                     out it writes an empty ``androidBuildToolsVersion`` into
                     gradle.properties, on which Gradle stops with "Invalid
                     revision". Measured against Qt 6.11.1.

    Returns:
        The path written.
    """
    settings = deployment_settings(project, env, app=app, primary=primary)
    if package_name is not None:
        settings["android-package-name"] = package_name
    if package_source_dir is not None:
        directory = Path(package_source_dir)
        if not directory.is_absolute():
            directory = Path(project.root_dir) / directory
        settings["android-package-source-directory"] = str(directory)
    if permissions:
        settings["permissions"] = [{"name": name} for name in permissions]
    if build_tools is not None:
        settings["sdkBuildToolsRevision"] = build_tools

    if output is None:
        primary_env = _abi_environments(env, primary)[0][settings["abi"]][0]
        output = (
            Path(primary_env.get("build_dir", "build"))
            / "android-deployment-settings.json"
        )
    output = Path(output)
    if not output.is_absolute():
        output = Path(project.root_dir) / output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(settings, indent=3) + "\n", encoding="utf-8")
    return output
