#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""An Android APK, cross-compiled and signed, without Gradle.

Every packaging step here is a host tool consuming a target artifact:
aapt2, zipalign and apksigner run on the build machine, and the library
they package was compiled for aarch64-linux-android. That is what
``tool=`` is for -- it names the program that runs a command, keeps it out
of ``$SOURCES``, and spells it the way the shell will execute it, so
nothing below writes a "./" or a platform conditional.

What it shows:

1. An Android cross environment from ``android()``, which finds its
   compiler under the NDK for this host.
2. Target-aware naming: the library comes out as ``libnative.so`` because
   the environment builds for Android. Nothing here sets a suffix.
3. Four installed host tools driven with ``tool=``, three of them absolute
   paths under the SDK and one (``keytool``) a name on ``$PATH``.
4. A debug keystore generated by the build, so the example is
   self-contained and identical on every machine.

Gradle is not used and not needed: the SDK build tools package an APK on
their own. The manifest says ``android:hasCode="false"``, so there is no
Java, no ``classes.dex``, and ``d8`` never runs.

    pcons                      # build and sign build/apk/app-debug.apk

Needs an Android NDK and SDK, named by ANDROID_NDK_HOME (or
ANDROID_NDK_ROOT) and ANDROID_HOME (or ANDROID_SDK_ROOT), plus a JDK for
keytool and apksigner.
"""

import os
import sys
from pathlib import Path

from pcons import Project
from pcons.toolchains.presets import android

ABI = "arm64-v8a"
API = 24


def _from_env(*names: str) -> Path:
    for name in names:
        value = os.environ.get(name)
        if value:
            return Path(value)
    raise SystemExit(f"Set one of {', '.join(names)} to build this example.")


def _newest(directory: Path) -> Path:
    entries = sorted(p for p in directory.iterdir() if p.is_dir())
    if not entries:
        raise SystemExit(f"Nothing installed under {directory}.")
    return entries[-1]


ndk = _from_env("ANDROID_NDK_HOME", "ANDROID_NDK_ROOT")
sdk = _from_env("ANDROID_HOME", "ANDROID_SDK_ROOT")
build_tools = _newest(sdk / "build-tools")
android_jar = _newest(sdk / "platforms") / "android.jar"

project = Project("android_apk")

target = project.Environment(toolchain="llvm", name="android")
target.build_prefix = "android"
target.library_directory = "lib"
target.apply_cross_preset(android(ndk=str(ndk), arch=ABI, api=API, sdk=str(sdk)))

native = project.SharedLibrary("native", target, sources=["src/native.c"])

host = project.Environment(name="host")
host.build_prefix = "apk"
host.ANDROID_JAR = str(android_jar)

base = host.Command(
    name="aapt2-link",
    target="base.apk",
    tool=build_tools / "aapt2",
    source=["AndroidManifest.xml"],
    command="$TOOL link -o $TARGET -I $ANDROID_JAR --manifest $SOURCE",
)

unaligned = host.Command(
    name="apk-libs",
    target="unaligned.apk",
    tool=sys.executable,
    source=[base, native],
    command=f"$TOOL $SRCDIR/tools/pack_libs.py ${{SOURCES[0]}} $TARGET {ABI} ${{SOURCES[1]}}",
    depends=["tools/pack_libs.py"],
)

aligned = host.Command(
    name="apk-align",
    target="aligned.apk",
    tool=build_tools / "zipalign",
    source=[unaligned],
    command="$TOOL -p -f 4 $SOURCE $TARGET",
)

keystore = host.Command(
    name="debug-keystore",
    target="debug.keystore",
    tool="keytool",
    command=[
        "$TOOL",
        "-genkeypair",
        "-keystore",
        "$TARGET",
        "-storepass",
        "android",
        "-keypass",
        "android",
        "-alias",
        "androiddebugkey",
        "-keyalg",
        "RSA",
        "-keysize",
        "2048",
        "-validity",
        "10000",
        "-dname",
        "CN=Android Debug,O=Android,C=US",
    ],
)

apk = host.Command(
    name="apk-sign",
    target="app-debug.apk",
    tool=build_tools / "apksigner",
    source=[aligned, keystore],
    command=[
        "$TOOL",
        "sign",
        "--ks",
        "${SOURCES[1]}",
        "--ks-pass",
        "pass:android",
        "--key-pass",
        "pass:android",
        "--ks-key-alias",
        "androiddebugkey",
        "--out",
        "$TARGET",
        "${SOURCES[0]}",
    ],
)

project.Default(native, apk)
