# SPDX-License-Identifier: MIT
"""GNU Makefile generator for pcons.

Generates Makefiles from a configured pcons Project.
Requires GNU Make 3.80+ for order-only prerequisites.
"""

from __future__ import annotations

import re
import shlex
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any, TextIO, cast

from pcons.core.node import AliasNode, FileNode, Node
from pcons.core.paths import PathResolver
from pcons.generators.generator import BaseGenerator, apply_context_overrides

if TYPE_CHECKING:
    from pcons.core.environment import Environment
    from pcons.core.project import Project
    from pcons.core.target import Target


class MakefileGenerator(BaseGenerator):
    """Generator that produces GNU Makefiles.

    Writes a complete Makefile: variables, directory rules, build rules,
    phony aliases, depfile includes, and a clean target. Requires GNU
    Make 3.80+ for order-only prerequisites.
    """

    _supports_compile_commands = True
    _is_build_generator = True

    # Characters that need escaping in Makefiles
    # $ -> $$, # -> \#, spaces in targets need escaping
    ESCAPE_DOLLAR = re.compile(r"\$")

    def __init__(self) -> None:
        super().__init__("makefile")
        self._directories: set[Path] = set()
        self._depfile_dirs: set[Path] = set()
        self._project_root: Path | None = None
        self._build_dir: Path | None = None
        self._relative_build_dir: Path | None = None
        self._path_resolver: PathResolver | None = None  # Set during generate()

    def _generate_impl(self, project: Project, output_dir: Path) -> None:
        """Generate Makefile in output_dir."""
        output_dir.mkdir(parents=True, exist_ok=True)
        makefile_path = output_dir / "Makefile"

        # Reset state for this generation
        self._directories = set()
        self._depfile_dirs = set()
        self._project_root = project.root_dir.resolve()
        self._build_dir = output_dir
        self._relative_build_dir = project.build_dir
        self._path_resolver = getattr(project, "_path_resolver", None)

        with open(makefile_path, "w", encoding="utf-8") as f:
            self._write_header(f, project)
            self._write_variables(f, project, output_dir)
            self._write_phony_declaration(f, project)
            self._collect_directories(project)
            self._write_directory_rules(f)
            self._write_build_rules(f, project)
            self._write_regen(f, project, makefile_path)
            self._write_aliases(f, project)
            self._write_tests(f, project)
            self._write_default_target(f, project)
            self._write_depfile_includes(f)
            self._write_clean_target(f, output_dir)

    def _write_header(self, f: TextIO, project: Project) -> None:
        """Write file header comment."""
        f.write(f"# Generated by pcons for project: {project.name}\n")
        f.write("# Do not edit - regenerate with 'pcons generate'\n")
        f.write("\n")
        # Disable built-in rules for cleaner output and faster make
        f.write("# Disable built-in rules\n")
        f.write(".SUFFIXES:\n")
        f.write("MAKEFLAGS += --no-builtin-rules\n")
        f.write("\n")

    def _write_variables(self, f: TextIO, project: Project, output_dir: Path) -> None:
        """Write global variables."""
        f.write("# Variables\n")
        f.write(f"BUILDDIR := {self._escape_path(output_dir)}\n")
        f.write("\n")

    def _write_phony_declaration(self, f: TextIO, project: Project) -> None:
        """Write .PHONY declaration for all phony targets."""
        phony_targets = ["all", "clean", *project.tree_aliases]
        if any(t.target_type == "test" for t in project.targets):
            phony_targets.extend(["test", "test-build"])
        f.write("# Phony targets\n")
        f.write(f".PHONY: {' '.join(phony_targets)}\n")
        f.write("\n")

    def _collect_directories(self, project: Project) -> None:
        """Collect all directories that need to be created."""
        # Collect from targets
        for target in project.targets:
            for node in self._get_target_build_nodes(target):
                parent = node.path.parent
                if (
                    parent != Path(".")
                    and parent != Path("")
                    and node.role != "install_output"
                ):
                    self._directories.add(parent)
                # Track depfile directories
                build_info = getattr(node, "_build_info", None) or {}
                depfile = build_info.get("depfile")
                if depfile:
                    from pcons.core.subst import PathToken

                    if isinstance(depfile, PathToken):
                        # PathToken: construct path from path + suffix
                        depfile_path = Path(depfile.path + depfile.suffix)
                        self._depfile_dirs.add(depfile_path.parent)

        # Collect from environment-tracked nodes
        for env in project.environments:
            for node in getattr(env, "_created_nodes", []):
                if isinstance(node, FileNode):
                    parent = node.path.parent
                    if parent != Path(".") and parent != Path(""):
                        self._directories.add(parent)

    def _write_directory_rules(self, f: TextIO) -> None:
        """Write rules to create directories."""
        if not self._directories:
            return

        f.write("# Directory creation\n")
        for directory in sorted(self._directories):
            escaped = self._make_build_relative_path(directory)
            f.write(f"{escaped}:\n")
            f.write('\tmkdir -p "$@"\n')
            f.write("\n")

    def _write_build_rules(self, f: TextIO, project: Project) -> None:
        """Write all build rules."""
        f.write("# Build rules\n")
        written_nodes: set[Path] = set()

        for target in project.targets:
            self._write_target_builds(f, target, project, written_nodes)

        # Also write builds for nodes tracked in environments
        for env in project.environments:
            for node in getattr(env, "_created_nodes", []):
                if isinstance(node, FileNode) and node.builder is not None:
                    if node.path not in written_nodes:
                        self._write_build_rule(f, node, None, project)
                        written_nodes.add(node.path)

        f.write("\n")

    def _write_target_builds(
        self,
        f: TextIO,
        target: Target,
        project: Project,
        written_nodes: set[Path],
    ) -> None:
        """Write build rules for a single target."""
        for node in self._get_target_build_nodes(target):
            if node.path not in written_nodes:
                self._write_build_rule(f, node, target, project)
                written_nodes.add(node.path)

    def _write_build_rule(
        self,
        f: TextIO,
        node: FileNode,
        target: Target | None,
        project: Project,
    ) -> None:
        """Write a single build rule."""
        build_info = getattr(node, "_build_info", None)
        if build_info is None:
            return

        # Skip secondary nodes from multi-output builds (they reference primary_node)
        if "primary_node" in build_info:
            return

        sources: list[Node] = build_info.get("sources", [])

        outputs_info = build_info.get("outputs")
        all_targets = build_info.get("all_targets")
        if outputs_info:
            all_outputs = [
                self._make_build_relative_path(info["path"])
                for info in outputs_info.values()
            ]
            output = " ".join(all_outputs)
        elif all_targets and len(all_targets) > 1:
            # A command with several declared outputs (e.g. a code generator):
            # name them all, or the extra ones have no rule at all.
            output = " ".join(
                self._node_path(n) for n in all_targets if isinstance(n, FileNode)
            )
        else:
            output = self._node_path(node)

        # Build outputs are build-dir-relative; source files are absolute so
        # they work from any directory.
        def get_source_path(s: FileNode) -> str:
            if getattr(s, "role", None) == "install_output":
                return self._node_path(s)
            if getattr(s, "_build_info", None) is not None or s.is_target:
                return self._make_build_relative_path(s.path)

            path_obj = s.path
            if not path_obj.is_absolute() and self._project_root is not None:
                path_obj = self._project_root / path_obj
            return self._escape_path(path_obj)

        prereqs: list[str] = []

        for s in sources:
            if isinstance(s, FileNode):
                prereqs.append(get_source_path(s))

        # Explicit deps (e.g. libraries for linking, generated headers) and
        # implicit deps (headers found by scanners, files named by depends=).
        # Rendered like sources: a dep may just as well be a source-tree file,
        # which make can't find by a build-dir-relative path.
        source_paths_set = {s.path for s in sources if isinstance(s, FileNode)}
        for dep in [*node.explicit_deps, *node.implicit_deps]:
            if isinstance(dep, FileNode) and dep.path not in source_paths_set:
                prereqs.append(get_source_path(dep))

        # Order-only prerequisites: the output directory, plus any dep that
        # only has to exist first (make's `|` is ninja's `||`).
        order_only: list[str] = []
        output_dir = node.path.parent
        if (
            output_dir != Path(".")
            and output_dir != Path("")
            and node.role != "install_output"
        ):
            order_only.append(self._make_build_relative_path(output_dir))
        prereq_set = set(prereqs)
        for dep in node.order_only_deps:
            if isinstance(dep, FileNode):
                path = get_source_path(dep)
                if path not in prereq_set:
                    order_only.append(path)

        prereq_str = " ".join(prereqs)
        if order_only:
            order_only_str = " | " + " ".join(order_only)
        else:
            order_only_str = ""

        f.write(f"{output}: {prereq_str}{order_only_str}\n")

        command = self._get_command(node, target, project, sources)
        if command:
            f.write(f"\t{self._escape_dollar_for_recipe(command)}\n")

        f.write("\n")

    def _get_command(
        self,
        node: FileNode,
        target: Target | None,
        project: Project,
        sources: list[Node],
    ) -> str:
        """Get the build command for a node."""
        build_info = getattr(node, "_build_info", {})
        tool_name = build_info.get("tool", "unknown")
        command_var = build_info.get("command_var", "cmdline")

        env: Environment | None = None
        if target is not None:
            env = getattr(target, "_env", None)

        if env is None:
            # e.g., Install nodes store env in build_info
            env = build_info.get("env")

        if env is None:
            for e in project.environments:
                if node in getattr(e, "_created_nodes", []):
                    env = e
                    break

        # Builder-provided command (generic commands, install, archive)
        custom_command = build_info.get("command")
        cwd = cast("Path | None", build_info.get("cwd"))
        if custom_command:
            if isinstance(custom_command, list):
                # Flags a builder appended to this edge (an install mode, a
                # module-mapper path). Ninja adds them the same way.
                extra = cast("list[str]", build_info.get("extra_command_flags") or [])
                custom_command = list(custom_command) + [
                    flag for flag in extra if flag not in custom_command
                ]
                processed_tokens = self._process_path_tokens(
                    custom_command,
                    cwd=cwd,
                    node_vars=cast("dict[str, object] | None", build_info.get("vars")),
                )

                # Expand $SOURCES/$TARGET before to_shell_command() so each
                # path is a separate, individually quoted token.
                expanded_tokens = self._expand_source_target_tokens(
                    processed_tokens, node, sources, build_info, cwd=cwd
                )

                from pcons.core.subst import to_shell_command

                # Launchers (ccache, a profiler) run in front of the command,
                # passed through as written: they are a program and its
                # arguments, not paths this edge builds from.
                launcher = cast("list[str]", build_info.get("launcher") or [])
                command = to_shell_command([*launcher, *expanded_tokens], shell="bash")
            else:
                command = str(custom_command)
                command = self._convert_command_variables(command)
                command = self._substitute_make_vars(command, node, sources, build_info)
            if cwd is not None:
                command = self._run_in_dir(command, cwd)
            return self._wrap_build_commands(command, node, target, sources)

        context = build_info.get("context")
        context_overrides: dict[str, object] = {}
        if context is not None and hasattr(context, "get_env_overrides"):
            context_overrides = context.get_env_overrides()

        if env is None:
            # Standalone tools (install, archive) need no environment
            from pcons.tools.tool import standalone_tool_tokens

            cmd_template = standalone_tool_tokens(tool_name, command_var)
            if cmd_template is None:
                return f"@echo 'No environment for {node.path}'"

            from pcons.core.subst import to_shell_command

            processed_tokens = self._process_path_tokens(
                cmd_template,
                node_vars=cast("dict[str, object] | None", build_info.get("vars")),
            )

            if context_overrides:
                processed_tokens = apply_context_overrides(
                    processed_tokens, tool_name, context_overrides
                )

            expanded_tokens = self._expand_source_target_tokens(
                processed_tokens, node, sources, build_info
            )

            command = to_shell_command(expanded_tokens, shell="bash")
            return self._wrap_build_commands(command, node, target, sources)

        tool_config = getattr(env, tool_name, None)
        if tool_config is None:
            return f"@echo 'Unknown tool: {tool_name}'"

        command_template = getattr(tool_config, command_var, None)
        if command_template is None:
            return f"@echo 'No command template: {tool_name}.{command_var}'"

        # Use raw subst() for tokens, not env.subst(), so PathTokens can be
        # relativized for make before shell quoting.
        from pcons.core.subst import subst as subst_fn
        from pcons.core.subst import to_shell_command

        # Mock envs in tests may lack _build_namespace
        if hasattr(env, "_build_namespace"):
            namespace = env._build_namespace()
            tokens = subst_fn(command_template, namespace)

            relativized_tokens = self._process_path_tokens(
                tokens,
                node_vars=cast("dict[str, object] | None", build_info.get("vars")),
            )

            # Expand $SOURCES/$TARGET before to_shell_command() so each
            # path is a separate, individually quoted token.
            expanded_tokens = self._expand_source_target_tokens(
                relativized_tokens, node, sources, build_info
            )

            command = to_shell_command(expanded_tokens, shell="bash")
        else:
            # Fallback for mock objects or non-standard environments
            command = env.subst(command_template, shell="bash")
            command = self._convert_command_variables(command)
            command = self._substitute_make_vars(command, node, sources, build_info)

        return self._wrap_build_commands(command, node, target, sources)

    def _write_regen(self, f: TextIO, project: Project, makefile_path: Path) -> None:
        """Write the rule that re-runs pcons when the build description changes.

        Make remakes any makefile it can build a rule for, then restarts
        itself — the same contract as Ninja's ``generator = 1`` edge, so
        staged generation works here too.
        """
        from pcons.core import invocation
        from pcons.core.subst import to_shell_command

        deps = project.configure_dependencies
        if not deps:
            return

        inv = invocation.current()
        if inv is None:
            return
        argv = inv.command(root_dir=project.root_dir, run_dir=makefile_path.parent)
        if argv is None:
            return

        dep_refs = " ".join(sorted(self._escape_path(self._regen_dep(d)) for d in deps))
        command = self._escape_dollar_for_recipe(to_shell_command(argv, shell="bash"))

        f.write("# Re-run pcons when the build description changes\n")
        f.write(f"Makefile: {dep_refs}\n")
        f.write('\t@echo "Regenerating $@"\n')
        f.write(f"\t{command}\n")
        f.write("\n")

    def _regen_dep(self, path: Path) -> str:
        """Render a configure dependency for the makefile-remake rule.

        Build-tree inputs must match how their producing rule names them
        (relative to the build dir, where make runs); source-tree inputs are
        absolute, like every other source path in the makefile.
        """
        build_parts = self._relative_build_dir.parts if self._relative_build_dir else ()
        if build_parts and path.parts[: len(build_parts)] == build_parts:
            return self._strip_build_dir_prefix(path)
        return self._relativize_path_for_make(str(path))

    def _wrap_build_commands(
        self,
        command: str,
        node: FileNode,
        target: Target | None,
        sources: list[Node],
    ) -> str:
        """Wrap with the target's pre/post-build commands (output nodes only).

        ``$out``/``$in`` expand to execution-relative paths, matching what the
        main command sees — make runs from the build directory.

        The test is ``output_nodes`` alone: ``Target.nodes`` also holds the
        intermediates, so testing it would put a post-build step meant for a
        linked library onto every object file the target compiles. An
        ObjectLibrary's objects *are* its outputs, so they still qualify.
        """
        if target is None or node not in target.output_nodes:
            return command

        builder_data = getattr(target, "_builder_data", {}) or {}
        pre_build_cmds = builder_data.get("pre_build_commands", [])
        post_build_cmds = builder_data.get("post_build_commands", [])
        if not pre_build_cmds and not post_build_cmds:
            return command

        out_path = self._node_out_raw(node)
        in_paths = " ".join(
            self._relativize_path_for_make(str(s.path))
            for s in sources
            if isinstance(s, FileNode)
        )

        def substitute(commands: list[str]) -> list[str]:
            return [
                cmd.replace("$out", out_path).replace("$in", in_paths)
                for cmd in commands
            ]

        parts = [*substitute(pre_build_cmds), command, *substitute(post_build_cmds)]
        return " && ".join(parts)

    def _escape_dollar_for_recipe(self, text: str) -> str:
        """Escape literal ``$`` as ``$$`` in a Makefile recipe line.

        Make's ``$``-expansion pass runs before the shell sees the line and
        ignores shell quotes, so even ``'-Wl,-rpath,$ORIGIN/../lib'`` needs
        its ``$`` doubled.
        """
        return self.ESCAPE_DOLLAR.sub("$$", text)

    def _substitute_make_vars(
        self,
        command: str,
        node: FileNode,
        sources: list[Node],
        build_info: dict[str, object],
    ) -> str:
        """Substitute $in/$out with explicit paths (not Make automatic vars,
        whose semantics don't match our source lists exactly).

        $in includes both sources and explicit_deps, matching ninja's $in.
        """

        in_paths: list[str] = []

        for s in sources:
            if isinstance(s, FileNode):
                in_paths.append(self._input_path(s))

        source_paths_set = {s.path for s in sources if isinstance(s, FileNode)}
        for dep in node.explicit_deps:
            if isinstance(dep, FileNode) and dep.path not in source_paths_set:
                in_paths.append(self._input_path(dep))

        source_paths = " ".join(in_paths)

        # $out is role-aware so the recipe writes exactly where the rule
        # target points.
        command = command.replace("$in", source_paths)
        command = command.replace("$out", self._node_out_raw(node))

        depfile = build_info.get("depfile")
        if depfile:
            from pcons.core.subst import PathToken

            if isinstance(depfile, PathToken):
                depfile_actual = depfile.path + depfile.suffix
                command = command.replace(
                    "$out.d", self._strip_build_dir_prefix(depfile_actual)
                )

        return command

    def _write_aliases(self, f: TextIO, project: Project) -> None:
        """Write alias targets, merged across the project tree."""
        aliases = project.tree_aliases
        if not aliases:
            return

        f.write("# Aliases\n")
        for name, nodes in aliases.items():
            members: list[str] = []
            for t in nodes:
                if isinstance(t, AliasNode):
                    # An alias may group other aliases: every alias name is
                    # already declared .PHONY, so it works as a prerequisite.
                    members.append(t.alias_name)
                elif isinstance(t, FileNode):
                    members.append(self._node_path(t))
            if members:
                f.write(f"{name}: {' '.join(members)}\n")
        f.write("\n")

    def _write_tests(self, f: TextIO, project: Project) -> None:
        """Emit ``test-build`` (compile tests) and ``test`` (run them) phonies.

        Emits nothing if the project declared no tests. Embeds
        ``sys.executable`` so the runner can import pcons regardless of
        what ``python`` is on PATH.
        """
        test_targets = [t for t in project.targets if t.target_type == "test"]
        if not test_targets:
            return

        program_outputs: list[str] = []
        seen: set[str] = set()
        for test_target in test_targets:
            for dep in test_target.dependencies:
                for node in dep.output_nodes:
                    if isinstance(node, FileNode):
                        out = self._make_build_relative_path(node.path)
                        if out not in seen:
                            seen.add(out)
                            program_outputs.append(out)

        f.write("# Tests\n")
        f.write(f"test-build: {' '.join(program_outputs)}\n")
        # Shell-quote (interpreter path may have spaces) and $-escape for Make
        python_exe = shlex.quote(sys.executable.replace("\\", "/"))
        python_exe = self._escape_dollar_for_recipe(python_exe)
        f.write("test: test-build\n")
        f.write(
            f"\t{python_exe} -m pcons.test_runner --manifest=tests.json --no-color\n"
        )
        f.write("\n")

    def _write_default_target(self, f: TextIO, project: Project) -> None:
        """Write the default and 'all' targets."""
        user_defaults: list[str] = []

        for target in project.default_targets:
            if target.output_nodes:
                for out_node in target.output_nodes:
                    if isinstance(out_node, FileNode):
                        user_defaults.append(self._node_path(out_node))
            else:
                for target_node in target.nodes:
                    if isinstance(target_node, FileNode):
                        user_defaults.append(self._node_path(target_node))

        # Collect all target outputs for 'all' (utility targets with
        # build_by_default=False are only built when requested).
        all_outputs: list[str] = []
        for target in project.targets:
            if not getattr(target, "build_by_default", True):
                continue
            if getattr(target, "_resolved", False):
                for node in target.output_nodes:
                    if isinstance(node, FileNode):
                        all_outputs.append(self._node_path(node))

        # If no resolved targets, find final nodes from env-created nodes
        if not all_outputs:
            all_outputs = self._find_final_nodes(project)

        # Collect programs and libraries for implicit default
        prog_lib_outputs: list[str] = []
        if not user_defaults:
            for target in project.targets:
                if not getattr(target, "build_by_default", True):
                    continue
                if getattr(target, "_resolved", False):
                    if target.target_type in (
                        "program",
                        "shared_library",
                        "static_library",
                    ):
                        for node in target.output_nodes:
                            if isinstance(node, FileNode):
                                prog_lib_outputs.append(
                                    self._make_build_relative_path(node.path)
                                )

        # Write targets
        f.write("# Default target\n")

        # Determine what 'make' with no args builds
        defaults = user_defaults or prog_lib_outputs or all_outputs
        if defaults:
            f.write(f"default: {' '.join(defaults)}\n")
            f.write(".DEFAULT_GOAL := default\n")

        # 'make all' builds every target in the project
        if all_outputs:
            f.write(f"all: {' '.join(all_outputs)}\n")

        f.write("\n")

    def _find_final_nodes(self, project: Project) -> list[str]:
        """Find output nodes nothing depends on, for builds that create
        nodes directly without registering targets."""
        output_nodes: set[Path] = set()
        dependency_nodes: set[Path] = set()

        for env in project.environments:
            for node in getattr(env, "_created_nodes", []):
                if isinstance(node, FileNode) and node.builder is not None:
                    output_nodes.add(node.path)
                    build_info = getattr(node, "_build_info", None) or {}
                    for source in build_info.get("sources", []):
                        if isinstance(source, FileNode):
                            dependency_nodes.add(source.path)
                    for dep in node.explicit_deps:
                        if isinstance(dep, FileNode):
                            dependency_nodes.add(dep.path)

        final_nodes = output_nodes - dependency_nodes
        return [self._make_build_relative_path(path) for path in sorted(final_nodes)]

    def _write_depfile_includes(self, f: TextIO) -> None:
        """Write includes for dependency files."""
        if not self._directories:
            return

        f.write("# Include dependency files (generated by compiler -MD flag)\n")
        for directory in sorted(self._directories):
            f.write(f"-include {self._make_build_relative_path(directory)}/*.d\n")
        f.write("\n")

    def _write_clean_target(self, f: TextIO, output_dir: Path) -> None:
        """Write the clean target."""
        f.write("# Clean target\n")
        f.write("clean:\n")
        f.write(f"\trm -rf {self._escape_path(output_dir)}\n")

    def _input_path(self, s: FileNode) -> str:
        """Render an input node for a recipe command line.

        Build artifacts are build-dir-relative; sources are absolute so they
        work from any directory. Must classify nodes the same way as the
        prerequisite list in _write_build_rule, or a recipe would name a
        file its rule doesn't depend on.
        """
        if getattr(s, "_build_info", None) is not None or s.is_target:
            return self._strip_build_dir_prefix(s.path)
        path_obj = s.path
        if not path_obj.is_absolute() and self._project_root is not None:
            path_obj = self._project_root / path_obj
        return str(path_obj)

    def _strip_build_dir_prefix(self, path: Path | str) -> str:
        """Strip the build_dir prefix from a path, since make runs from the
        build dir (contract: pcons.core.paths.execution_relative)."""
        if self._path_resolver is not None:
            return self._path_resolver.make_execution_relative(path)
        # Resolver-less project (tests with bare stubs)
        from pcons.core.paths import execution_relative

        return execution_relative(
            path,
            execution_dir=self._build_dir,
            build_dir_parts=self._relative_build_dir.parts
            if self._relative_build_dir
            else (),
        )

    def _escape_path(self, path: Path | str) -> str:
        """Escape a path for a position where make parses names.

        Targets, prerequisites and include lines are split on whitespace, so a
        space in a path has to be escaped or make reads one name as several.
        `$` doubles, as everywhere in a makefile. A backslash-escaped space
        also survives into a recipe unharmed, since that is what the shell
        wants too.
        """
        path_str = self.ESCAPE_DOLLAR.sub("$$", str(path))
        return path_str.replace(" ", "\\ ")

    def _make_build_relative_path(self, path: Path | str) -> str:
        """Strip the build_dir prefix and escape for a make name position."""
        return self._escape_path(self._strip_build_dir_prefix(path))

    def _node_out_raw(self, node: FileNode) -> str:
        """Return the unescaped output path for *node*, honoring its role.

        Install outputs live outside the build dir and are emitted absolute;
        other nodes are build-dir-relative. Returned unescaped so rule
        targets and recipe tokens (escaped separately) agree on the path.
        """
        if node.role == "install_output":
            p = node.path
            if not p.is_absolute() and self._project_root is not None:
                p = self._project_root / p
            return str(p)
        return self._strip_build_dir_prefix(node.path)

    def _node_path(self, node: FileNode) -> str:
        """Render a Makefile rule-target path for *node*, escaped for make."""
        return self._escape_path(self._node_out_raw(node))

    def _run_in_dir(self, command: str, cwd: Path) -> str:
        """Wrap *command* so it runs in *cwd*, and come back afterwards.

        Make runs from the build directory, and the pre/post-build commands
        wrapped around this one name their files relative to it, so the ``cd``
        is paired with a ``cd`` back instead of leaking into the rest of the
        recipe line. Both are absolute: a Makefile already spells its source
        paths absolutely, so there is no relocatability left to protect.
        """
        return f"cd {shlex.quote(str(cwd))} && {command} && cd {shlex.quote(str(self._build_dir))}"

    def _at_build_dir(self, path: str) -> str:
        """A recipe path made absolute, for a command that runs elsewhere.

        Recipe paths are either build-dir-relative (build artifacts) or
        already absolute (source-tree files).
        """
        path_obj = Path(path)
        if path_obj.is_absolute() or self._build_dir is None:
            return str(path_obj)
        return str(self._build_dir / path_obj)

    def _process_path_tokens(
        self,
        tokens: list,
        *,
        cwd: Path | None = None,
        node_vars: dict[str, object] | None = None,
    ) -> list:
        """Relativize PathTokens in a command token list for make.

        SourcePath/TargetPath markers pass through unchanged for
        _expand_source_target_tokens() to handle. A NodeVar expands to its
        value here: make has no per-edge variables, so the value goes inline,
        and expanding it before the loop means its own paths are relativized
        with everything else.
        """
        from pcons.core.subst import NodeVar, PathToken, SourcePath, TargetPath

        expanded: list = []
        for token in tokens:
            if isinstance(token, NodeVar):
                value = (node_vars or {}).get(token.name, "")
                expanded.extend(value if isinstance(value, list) else [value])
            else:
                expanded.append(token)
        tokens = expanded

        def relativize(path: str) -> str:
            rendered = self._relativize_path_for_make(path)
            return self._at_build_dir(rendered) if cwd is not None else rendered

        result: list = []
        for token in tokens:
            if isinstance(token, (SourcePath, TargetPath)):
                result.append(token)
            elif isinstance(token, PathToken):
                result.append(token.relativize(relativize))
            else:
                s = str(token)
                # $SRCDIR becomes the absolute project root (make runs from
                # the build dir)
                if "$SRCDIR" in s and self._project_root:
                    s = s.replace("$SRCDIR", str(self._project_root))
                result.append(s)
        return result

    def _relativize_path_for_make(self, path: str) -> str:
        """Transform a path for make's execution context: "." for the build
        dir, build-relative below it, absolute for project paths."""
        path_obj = Path(path)

        if path_obj.is_absolute():
            return path

        if self._build_dir:
            build_dir_str = str(self._build_dir)
            if path == build_dir_str:
                return "."
            if path.startswith(build_dir_str + "/"):
                return path[len(build_dir_str) + 1 :]

        if self._project_root:
            return str(self._project_root / path)

        return path

    def _expand_source_target_tokens(
        self,
        tokens: list,
        node: FileNode,
        sources: list[Node],
        build_info: dict[str, object],
        *,
        cwd: Path | None = None,
    ) -> list[str]:
        """Expand source/target markers and $SOURCES/$TARGET-style variables
        to actual file paths at the token level.

        Expansion happens before shell quoting so each path becomes a
        separate, individually quoted token — critical for commands like
        linkers where $SOURCES expands to multiple files.

        With *cwd*, the command runs somewhere other than the build directory,
        so build-relative paths are made absolute — the one spelling that
        means the same thing from every directory.
        """
        from pcons.core.subst import SourcePath, TargetPath

        # All input paths (sources + explicit_deps)
        in_paths: list[str] = []
        for s in sources:
            if isinstance(s, FileNode):
                in_paths.append(self._input_path(s))
        source_paths_set = {s.path for s in sources if isinstance(s, FileNode)}
        for dep in node.explicit_deps:
            if isinstance(dep, FileNode) and dep.path not in source_paths_set:
                in_paths.append(self._input_path(dep))

        # Role-aware so install outputs resolve to their absolute
        # destination, matching the rule target.
        out_path = self._node_out_raw(node)

        depfile = build_info.get("depfile")
        depfile_path = ""
        if depfile:
            from pcons.core.subst import PathToken

            if isinstance(depfile, PathToken):
                depfile_path = self._strip_build_dir_prefix(
                    depfile.path + depfile.suffix
                )

        # All target paths for multi-output commands: all_targets (generic
        # commands) or outputs dict (MultiOutputBuilder)
        all_targets = build_info.get("all_targets")
        outputs_info = build_info.get("outputs")
        out_paths: list[str] = []
        if all_targets and isinstance(all_targets, list):
            for t in all_targets:
                path = getattr(t, "path", None)
                if path is not None:
                    out_paths.append(self._strip_build_dir_prefix(path))
        elif outputs_info and isinstance(outputs_info, dict):
            for _name, info in outputs_info.items():
                if isinstance(info, dict) and "path" in info:
                    info_dict = cast(dict[str, Any], info)
                    out_paths.append(self._strip_build_dir_prefix(info_dict["path"]))
        if not out_paths:
            out_paths = [out_path]

        if cwd is not None:
            in_paths = [self._at_build_dir(p) for p in in_paths]
            out_paths = [self._at_build_dir(p) for p in out_paths]
            out_path = self._at_build_dir(out_path)
            depfile_path = self._at_build_dir(depfile_path) if depfile_path else ""

        # An explicit index on any marker (even 0) switches all markers of
        # that type to indexed mode; index=None means "auto".
        has_indexed_source = any(
            isinstance(t, SourcePath) and (t.index is not None or t.is_slice)
            for t in tokens
        )
        has_indexed_target = any(
            isinstance(t, TargetPath) and (t.index is not None or t.is_slice)
            for t in tokens
        )

        result: list[str] = []
        for token in tokens:
            if isinstance(token, (SourcePath, TargetPath)) and token.is_slice:
                # A slice names a range of the edge's paths; make sees the
                # concrete paths anyway, so this is a plain list slice.
                paths = in_paths if isinstance(token, SourcePath) else out_paths
                result.extend(
                    f"{token.prefix}{p}{token.suffix}"
                    for p in paths[token.start : token.stop]
                )
            elif isinstance(token, SourcePath):
                if token.index is not None or has_indexed_source:
                    idx = token.index or 0
                    if idx < len(in_paths):
                        result.append(f"{token.prefix}{in_paths[idx]}{token.suffix}")
                    elif in_paths:
                        result.append(f"{token.prefix}{in_paths[0]}{token.suffix}")
                else:
                    for p in in_paths:
                        result.append(f"{token.prefix}{p}{token.suffix}")
            elif isinstance(token, TargetPath):
                if token.basename:
                    # Make substitutes concrete paths and shares no rules, so
                    # there is nothing to collapse here — just the filename.
                    result.append(f"{token.prefix}{Path(out_path).name}{token.suffix}")
                elif token.index is not None or has_indexed_target:
                    idx = token.index or 0
                    if idx < len(out_paths):
                        result.append(f"{token.prefix}{out_paths[idx]}{token.suffix}")
                    else:
                        result.append(f"{token.prefix}{out_path}{token.suffix}")
                else:
                    # Unindexed means every output, matching ninja's $out.
                    for p in out_paths or [out_path]:
                        result.append(f"{token.prefix}{p}{token.suffix}")
            # String patterns (legacy support)
            elif isinstance(token, str):
                if token in ("$SOURCES", "$SOURCE", "$in"):
                    result.extend(in_paths)
                elif token in ("$TARGET", "$TARGETS", "$out"):
                    result.extend(out_paths or [out_path])
                elif token in ("$TARGET.d", "$out.d"):
                    result.append(depfile_path if depfile_path else token)
                elif (
                    "$TARGET" in token
                    or "$SOURCE" in token
                    or "$in" in token
                    or "$out" in token
                ):
                    # Embedded variables like /Fo$TARGET or -MF$TARGET.d.
                    # Order matters: $TARGET.d/$out.d before $TARGET/$out,
                    # $TARGETS before $TARGET, $SOURCES before $SOURCE.
                    expanded = token
                    if "$TARGET.d" in expanded:
                        expanded = expanded.replace(
                            "$TARGET.d", depfile_path if depfile_path else "$TARGET.d"
                        )
                    if "$out.d" in expanded:
                        expanded = expanded.replace(
                            "$out.d", depfile_path if depfile_path else "$out.d"
                        )
                    if "$TARGETS" in expanded:
                        expanded = expanded.replace("$TARGETS", out_path)
                    if "$TARGET" in expanded:
                        expanded = expanded.replace("$TARGET", out_path)
                    if "$out" in expanded:
                        expanded = expanded.replace("$out", out_path)
                    if "$SOURCES" in expanded:
                        expanded = expanded.replace("$SOURCES", " ".join(in_paths))
                    if "$SOURCE" in expanded:
                        first_source = in_paths[0] if in_paths else ""
                        expanded = expanded.replace("$SOURCE", first_source)
                    if "$in" in expanded:
                        expanded = expanded.replace("$in", " ".join(in_paths))
                    result.append(expanded)
                else:
                    result.append(token)
            else:
                result.append(str(token))

        return result

    def _convert_command_variables(self, command: str) -> str:
        """Convert pcons template variables ($SOURCES, $TARGET, ...) to
        intermediate $in/$out, which _substitute_make_vars() later replaces
        with actual paths."""
        # Plural forms first, so they don't match singular
        command = command.replace("$SOURCES", "$in")
        command = command.replace("$TARGETS", "$out")

        command = command.replace("$SOURCE", "$in")
        # $TARGET_xxx (multi-output) before plain $TARGET
        command = re.sub(r"\$TARGET_(\w+)", r"$out_\1", command)
        command = command.replace("$TARGET.d", "$out.d")
        command = command.replace("$TARGET", "$out")

        # Indexed access has no Make equivalent; expand to all sources/targets
        command = re.sub(r"\$\{SOURCES\[\d+\]\}", "$in", command)
        command = re.sub(r"\$\{TARGETS\[\d+\]\}", "$out", command)

        return command
