# SPDX-License-Identifier: MIT
"""Ninja build file generator.

Generates build.ninja files from a configured pcons Project.

Typically used via the ``Generator()`` factory::

    from pcons import Generator
    Generator().generate(project)  # Ninja is the default

Direct use: ``NinjaGenerator().generate(project)``
"""

from __future__ import annotations

import hashlib
import logging
import os
import re
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any, TextIO, cast

from pcons.configure.platform import get_platform
from pcons.core.debug import trace, trace_value
from pcons.core.node import AliasNode, FileNode, Node
from pcons.core.paths import PathResolver
from pcons.core.subst import NodeVar
from pcons.generators.generator import BaseGenerator, apply_context_overrides

if TYPE_CHECKING:
    from pcons.core.environment import Environment
    from pcons.core.project import Project
    from pcons.core.subst import CommandToken
    from pcons.core.target import Target

logger = logging.getLogger(__name__)


class NinjaGenerator(BaseGenerator):
    """Generator that produces Ninja build files.

    Writes a complete build.ninja: variables, deduplicated rules, build
    statements, phony aliases, and default targets.
    """

    _supports_compile_commands = True
    _is_build_generator = True

    # Characters that need escaping in Ninja
    ESCAPE_CHARS = re.compile(r"([$:\s])")

    def __init__(self) -> None:
        super().__init__("ninja")
        self._rules: dict[str, str] = {}  # rule_name -> command
        self._rule_counter = 0
        self._output_dir: Path | None = None  # Set during generate()
        self._project_root: Path | None = None  # Set during generate()
        self._topdir: str = ".."  # Relative path from output_dir to project root
        self._path_resolver: PathResolver | None = None  # Set during generate()
        self._build_dir_parts: tuple[str, ...] = ()  # Parts of relative build_dir
        # Path-carrying flags of the project's toolchains (-I, -isystem, /I...)
        self._path_flags: frozenset[str] = frozenset()
        self._warned_absolute_paths: set[str] = set()
        self._warned_build_dir_paths: set[str] = set()
        # id(node) -> (rule_key, command); reset per generate()
        self._rule_key_cache: dict[int, tuple[str, str]] = {}

    def _generate_impl(self, project: Project, output_dir: Path) -> None:
        """Generate build.ninja in output_dir."""
        trace("generate", "Generating ninja files to: %s", output_dir)
        trace_value("generate", "targets", len(project.targets))

        output_dir.mkdir(parents=True, exist_ok=True)
        ninja_file = output_dir / "build.ninja"

        # Reset state for this generation
        self._rules = {}
        self._rule_counter = 0
        self._output_dir = output_dir.resolve()
        self._project_root = project.root_dir.resolve()
        self._path_resolver = getattr(project, "_path_resolver", None)
        self._build_dir_parts = Path(project.build_dir).parts
        self._path_flags = self._collect_path_flags(project)
        self._warned_absolute_paths = set()
        self._warned_build_dir_paths = set()
        self._rule_key_cache = {}
        try:
            self._topdir = str(
                Path(os.path.relpath(self._project_root, self._output_dir))
            )
        except ValueError:
            # On Windows, relpath fails for paths on different drives
            self._topdir = str(self._project_root)

        with open(ninja_file, "w", encoding="utf-8") as f:
            self._write_header(f, project)
            self._write_variables(f, project)
            self._write_rules(f, project)
            self._write_builds(f, project)
            self._write_regen(f, project, ninja_file)
            self._write_aliases(f, project)
            self._write_tests(f, project)
            self._write_defaults(f, project)

    def _write_header(self, f: TextIO, project: Project) -> None:
        """Write file header comment."""
        f.write(f"# Generated by pcons for project: {project.name}\n")
        f.write("# Do not edit - regenerate with 'pcons generate'\n")
        f.write("ninja_required_version = 1.10\n")
        f.write("\n")

    def _write_variables(self, f: TextIO, project: Project) -> None:
        """Write global variables."""
        f.write("# Global variables\n")
        # builddir is "." since the ninja file is in the build directory
        f.write("builddir = .\n")
        # topdir: relative path from build dir to project root
        f.write(f"topdir = {self._escape_path(self._topdir)}\n")
        f.write("\n")

    def _write_rules(self, f: TextIO, project: Project) -> None:
        """Write rule definitions (identical commands share a rule)."""
        f.write("# Rules\n")

        for target in project.targets:
            env = target._env
            for node in self._get_target_build_nodes(target):
                self._ensure_rule(f, node, target, env)

        # Also check nodes tracked in environments
        for env in project.environments:
            for node in getattr(env, "_created_nodes", []):
                if isinstance(node, FileNode) and (
                    node.builder is not None
                    or getattr(node, "_build_info", None) is not None
                ):
                    self._ensure_rule(f, node, None, env)

        f.write("\n")

    def _find_env_for_node(
        self, node: FileNode, project: Project
    ) -> Environment | None:
        """Find the environment that created a node."""
        for env in project.environments:
            if node in getattr(env, "_created_nodes", []):
                return env
        return None

    def _resolve_rule_key(
        self,
        node: FileNode,
        build_info: dict[str, Any],
        target: Target | None,
        env: Environment | None,
    ) -> tuple[str, str]:
        """Resolve the rule key and expanded command for a build node.

        Single source of truth for rule naming: both _ensure_rule() and
        _write_build_statement() use it, so the answer is memoized per node —
        the work (relativizing every token, quoting, wrapping, hashing) is the
        generator's dominant cost, and computing it twice also leaves room for
        the two answers to disagree.
        """
        cached = self._rule_key_cache.get(id(node))
        if cached is not None:
            return cached
        result = self._compute_rule_key(node, build_info, target, env)
        self._rule_key_cache[id(node)] = result
        return result

    def _compute_rule_key(
        self,
        node: FileNode,
        build_info: dict[str, Any],
        target: Target | None,
        env: Environment | None,
    ) -> tuple[str, str]:
        """The uncached body of :meth:`_resolve_rule_key`."""
        from pcons.core.subst import to_shell_command

        tool_name = build_info.get("tool", "unknown")
        command_var = build_info.get("command_var", "cmdline")
        custom_rule_name = build_info.get("rule_name")

        # Resolve the command string
        command_raw = build_info.get("command")
        extra_command_flags = build_info.get("extra_command_flags") or []
        cwd = cast("Path | None", build_info.get("cwd"))

        launcher = cast("list[str]", build_info.get("launcher") or [])

        if command_raw is None:
            command = self._expand_command_fallback(node, build_info, env)
        elif isinstance(command_raw, list):
            command_tokens = list(command_raw)
            for flag in extra_command_flags:
                if flag not in command_tokens:
                    command_tokens.append(flag)
            all_targets = build_info.get("all_targets") or []
            relativized_tokens = self._relativize_command_tokens(
                cast(list[str], command_tokens),
                source_count=len(build_info.get("sources") or []),
                target_count=len(all_targets) or 1,
                cwd=cwd,
            )
            # Launcher tokens are a program and its arguments, not paths in the
            # graph, so they are passed through as written rather than
            # rewritten for the execution directory. Quoting still applies.
            command = to_shell_command(
                [*launcher, *relativized_tokens],
                shell="ninja",
                extra_ninja_vars=frozenset(cast(dict, build_info.get("vars") or {})),
            )
        else:
            command = command_raw
            for flag in extra_command_flags:
                if f" {flag}" not in command:
                    command = f"{command} {flag}"
            if launcher:
                command = f"{to_shell_command(launcher, shell='ninja')} {command}"

        if cwd is not None:
            command = self._run_in_dir(command, cwd)

        # Wrap with the target's pre/post-build commands
        pre_build_prefix = self._get_pre_build_prefix(node, target)
        if pre_build_prefix:
            command = pre_build_prefix + command.lstrip()
        post_build_suffix = self._get_post_build_suffix(node, target)
        if post_build_suffix:
            command = command.rstrip() + post_build_suffix

        command = self._route_through_shell(command)

        # Compute rule key
        if custom_rule_name:
            rule_key = custom_rule_name
        else:
            # Rule behavior is affected not only by command text but also by
            # dependency parsing mode/restat. If we dedupe solely by command,
            # a module object (no depfile/deps) can accidentally share a rule
            # with a regular C++ object (gcc depfile), dropping headers tracking.
            depfile = build_info.get("depfile")
            deps_style = build_info.get("deps_style")
            restat = bool(build_info.get("restat"))

            dep_sig = "none"
            if deps_style == "msvc":
                dep_sig = "msvc"
            elif deps_style == "gcc":
                from pcons.core.subst import PathToken

                if isinstance(depfile, PathToken):
                    dep_sig = f"gcc:{depfile.suffix}"
                else:
                    dep_sig = "gcc"

            # The description is part of the rule, so two edges may only
            # share one if theirs agree.
            description = build_info.get("description") or ""
            hash_body = (
                f"{command}\n{dep_sig}\nrestat:{int(restat)}\ndesc:{description}"
            )
            cmd_hash = hashlib.md5(hash_body.encode()).hexdigest()[:8]
            rule_key = f"{tool_name}_{command_var}_{cmd_hash}"

        return rule_key, command

    def _ensure_rule(
        self,
        f: TextIO,
        node: FileNode,
        target: Target | None,
        env: Environment | None = None,
    ) -> str:
        """Ensure a rule exists for this node's builder, return rule name.

        Uses the resolver's pre-expanded command from _build_info["command"];
        nodes without one fall back to _expand_command_fallback().
        """
        build_info = getattr(node, "_build_info", None)
        if build_info is None:
            return "phony"

        if "primary_node" in build_info:
            # A secondary output of a multi-output edge: the primary node's
            # build statement lists it, so it needs no rule of its own.
            return "phony"

        tool_name = build_info.get("tool", "unknown")
        custom_rule_name = build_info.get("rule_name")

        rule_key, command = self._resolve_rule_key(node, build_info, target, env)

        if rule_key not in self._rules:
            rule_name = rule_key
            description = f"{tool_name.upper()} $out"

            # Use description from build_info if provided
            custom_description = build_info.get("description")
            if custom_description:
                description = str(custom_description)
            elif custom_rule_name:
                description = "COMMAND $out"

            # Write the rule
            f.write(f"rule {rule_name}\n")
            f.write(f"  command = {command}\n")
            f.write(f"  description = {description}\n")

            # Add depfile support based on builder configuration
            depfile = build_info.get("depfile")
            deps_style = build_info.get("deps_style")

            if deps_style == "msvc":
                f.write("  deps = msvc\n")
                # Ninja's default msvc_deps_prefix is the English
                # "Note: including file: " that cl.exe emits. On a
                # localized (e.g. German/Japanese) cl.exe this default
                # silently matches nothing and header deps are dropped, so
                # pin it explicitly rather than relying on ninja's default.
                f.write("  msvc_deps_prefix = Note: including file: \n")
            elif deps_style == "gcc":
                if depfile:
                    # depfile is a PathToken - use suffix to create $out.d pattern
                    # Ninja uses $out (the output variable) + suffix
                    from pcons.core.subst import PathToken

                    if isinstance(depfile, PathToken):
                        depfile_ninja = f"$out{depfile.suffix}"
                        f.write(f"  depfile = {depfile_ninja}\n")
                f.write("  deps = gcc\n")

            if build_info.get("restat"):
                f.write("  restat = 1\n")

            f.write("\n")
            self._rules[rule_key] = rule_name

        return self._rules[rule_key]

    # Shell operators that only mean anything to a shell. A command using one
    # has to be routed through one on Windows (see _route_through_shell).
    _SHELL_OPERATORS = (
        " && ",
        " || ",
        " | ",
        " > ",
        " >> ",
        " < ",
        # Stderr redirects are shell syntax too, and " > " is not a substring
        # of " 2> " -- without these a command whose only operator is one of
        # them goes to CreateProcess with the redirect as a literal argument.
        " 2> ",
        " 2>> ",
        " 2>&1 ",
        " >&2 ",
    )

    def _route_through_shell(self, command: str) -> str:
        """Run *command* through cmd.exe when it needs a shell, on Windows.

        Ninja hands a command to CreateProcess directly on Windows — there is
        no shell — so ``a && b`` reaches ``a`` as the literal arguments "&&"
        and "b", and silently does half the work. (On Unix ninja always uses
        /bin/sh, so nothing is needed there.) ``/s`` makes cmd strip exactly
        the outer quotes and leave the rest alone, so quoted arguments inside
        the command survive.
        """
        if not get_platform().is_windows:
            return command
        if not any(op in command for op in self._SHELL_OPERATORS):
            return command
        if command.startswith(("cmd ", "cmd.exe ")):
            return command  # already explicit about wanting a shell
        return f'cmd.exe /s /c "{command}"'

    def _run_in_dir(self, command: str, cwd: Path) -> str:
        """Wrap *command* so it runs in *cwd*, and come back afterwards.

        Ninja runs every edge from the build directory, and everything else on
        the command line counts on that: the pre/post-build commands wrapped
        around this one (``write_if_different``'s stash, say) name their files
        relative to it. So the ``cd`` is paired with a ``cd`` back rather than
        left to leak into the rest of the ``&&`` chain — a one-way ``cd`` is
        exactly the trap this argument exists to remove.

        Both directions are written relative to the build dir where possible,
        so build.ninja stays relocatable; only a directory no relative path
        can reach (another Windows drive) falls back to absolute.
        """
        cd = "cd /d" if get_platform().is_windows else "cd"
        there = self._dir_argument(cwd, base=self._output_dir)
        back = self._dir_argument(self._output_dir, base=cwd)
        return f"{cd} {there} && {command} && {cd} {back}"

    #: A directory a shell needs no help reading.
    _PLAIN_DIR = re.compile(r"^[\w./\\:-]+$")

    def _dir_argument(self, directory: Path | None, *, base: Path | None) -> str:
        """*directory* as a ``cd`` argument, seen from *base*.

        Quoted for the shell ninja will use — cmd.exe doesn't honour single
        quotes, /bin/sh keeps expanding inside double ones — and $-escaped for
        ninja itself.
        """
        rel = str(directory)
        if directory is not None and base is not None:
            try:
                rel = os.path.relpath(directory, base)
            except ValueError:
                rel = str(directory)  # different Windows drive
        windows = get_platform().is_windows
        # cmd.exe reads a leading "/" as a switch, so give it backslashes.
        rel = rel.replace("\\", "/").replace("/", "\\" if windows else "/")
        quote = '"' if windows else "'"
        escaped = rel.replace("$", "$$")
        if self._PLAIN_DIR.match(rel):
            return escaped
        return f"{quote}{escaped}{quote}"

    def _absolute(self, path: Path | str) -> Path:
        """The absolute location of a node path (build output or source).

        Node paths are project-root-relative and carry the build_dir prefix
        for outputs; both spellings resolve here so a path can be re-anchored
        to an edge's working directory.
        """
        path_obj = Path(str(path).replace("\\", "/"))
        if path_obj.is_absolute():
            return path_obj
        if self._is_under_build_dir(path_obj) and self._output_dir is not None:
            return self._output_dir / self._make_output_relative(path_obj)
        if self._project_root is not None:
            return self._project_root / path_obj
        return path_obj

    def _output_absolute(self, path: Path | str) -> Path:
        """The absolute location of a *build output*'s node path.

        An output's node path is execution-relative, which it can be either
        with the build_dir prefix (``build/gen/x.c``) or without it, when the
        builder was handed a bare name (``env.Command(target="out.txt")``).
        :meth:`_absolute` can't tell the second spelling from a source path
        and would anchor it at the project root, so an output resolves here
        instead: ``_make_output_relative`` normalizes both spellings.
        """
        path_obj = Path(str(path).replace("\\", "/"))
        if path_obj.is_absolute() or self._output_dir is None:
            return path_obj
        return self._output_dir / self._make_output_relative(path_obj)

    def _path_at(self, path: Path | str, cwd: Path, *, output: bool = False) -> str:
        """Render *path* as a command running in *cwd* sees it.

        Separators stay native on Windows. Everywhere else pcons writes
        forward slashes and ninja passes them through happily, but a moved
        edge always contains ``&&``, so it is routed through ``cmd.exe`` —
        which reads ``build/tool.exe`` as the command ``build`` with a
        ``/tool.exe`` switch. Only a re-anchored path can acquire a directory
        component it didn't have, so this is the one place it bites.
        """
        absolute = self._output_absolute(path) if output else self._absolute(path)
        try:
            rendered = os.path.relpath(absolute, cwd)
        except ValueError:
            rendered = str(absolute)  # different Windows drive
        if get_platform().is_windows:
            return rendered.replace("/", "\\")
        return rendered.replace("\\", "/")

    def _extra_build_commands(
        self,
        node: FileNode,
        target: Target | None,
        key: str,
    ) -> list[str]:
        """The target's pre/post-build commands, if *node* is an output node.

        These are baked into the rule command, so targets with different
        pre/post-build commands get different rules (via the command hash).
        $out and $in are left as literals for ninja to expand at build time:
        ninja runs from the build directory, so they are already
        build-dir-relative, matching the paths in the main command.

        The test is ``output_nodes`` alone: ``Target.nodes`` also holds the
        intermediates, so testing it would put a post-build step meant for a
        linked library onto every object file the target compiles. An
        ObjectLibrary's objects *are* its outputs, so they still qualify.
        """
        if target is None or node not in target.output_nodes:
            return []

        builder_data = getattr(target, "_builder_data", {}) or {}
        return list(builder_data.get(key, []))

    def _get_post_build_suffix(
        self,
        node: FileNode,
        target: Target | None,
    ) -> str:
        """Return ' && cmd1 && cmd2' for the target's post-build commands."""
        commands = self._extra_build_commands(node, target, "post_build_commands")
        return " && " + " && ".join(commands) if commands else ""

    def _get_pre_build_prefix(
        self,
        node: FileNode,
        target: Target | None,
    ) -> str:
        """Return 'cmd1 && cmd2 && ' for the target's pre-build commands."""
        commands = self._extra_build_commands(node, target, "pre_build_commands")
        return " && ".join(commands) + " && " if commands else ""

    def _expand_command_fallback(
        self,
        _node: FileNode,
        build_info: dict[str, Any],
        env: Environment | None,
    ) -> str:
        """Fallback command expansion when build_info["command"] is not set
        (manually-created _build_info or nodes that bypassed project.resolve()).
        """
        tool_name = build_info.get("tool", "unknown")
        command_var = build_info.get("command_var", "cmdline")
        context = build_info.get("context")

        # Check for context overrides (archive/install tools)
        context_overrides: dict[str, Any] = {}
        if context is not None and hasattr(context, "get_env_overrides"):
            context_overrides = context.get_env_overrides()

        # Default command
        command = f"echo 'No command for {tool_name}_{command_var}'"

        if env is not None:
            tool_config = getattr(env, tool_name, None)
            if tool_config is not None:
                cmd_template = getattr(tool_config, command_var, None)
                if cmd_template:
                    # Set context overrides on tool config
                    if context_overrides:
                        for key, val in context_overrides.items():
                            setattr(tool_config, key, val)

                    # Expand using subst
                    command = env.subst(cmd_template, shell="ninja")
        else:
            # Try standalone tools. Their context supplies what subst() would
            # have ($install.destdir and friends); it has to be applied to the
            # tokens, before quoting escapes the dollar it matches on.
            from pcons.core.subst import to_shell_command
            from pcons.tools.tool import standalone_tool_tokens

            tokens = standalone_tool_tokens(tool_name, command_var)
            if tokens is not None:
                if context_overrides:
                    tokens = apply_context_overrides(
                        tokens, tool_name, context_overrides
                    )
                command = to_shell_command(
                    self._relativize_command_tokens(tokens), shell="ninja"
                )

        return command

    def _write_builds(self, f: TextIO, project: Project) -> None:
        """Write build statements for all targets."""
        f.write("# Build statements\n")

        written_nodes: set[Path] = set()

        for target in project.targets:
            self._write_target_builds(f, target, project, written_nodes)

        # Also write builds for nodes tracked in environments
        for env in project.environments:
            for node in getattr(env, "_created_nodes", []):
                if isinstance(node, FileNode) and (
                    node.builder is not None
                    or getattr(node, "_build_info", None) is not None
                ):
                    if node.path not in written_nodes:
                        self._write_build_statement(f, node, None, project)
                        written_nodes.add(node.path)

        f.write("\n")

    def _write_target_builds(
        self, f: TextIO, target: Target, project: Project, written_nodes: set[Path]
    ) -> None:
        """Write build statements for a single target."""
        for node in self._get_target_build_nodes(target):
            if node.path not in written_nodes:
                self._write_build_statement(f, node, target, project)
                written_nodes.add(node.path)

    def _write_build_statement(
        self,
        f: TextIO,
        node: FileNode,
        target: Target | None,
        project: Project | None = None,
    ) -> None:
        """Write a single build statement.

        Multi-output builds use Ninja's implicit output syntax:
        build out1 out2 | implicit_out: rule deps
        """
        build_info = getattr(node, "_build_info", None)
        if build_info is None:
            return

        # Skip secondary nodes from multi-output builds (they reference primary_node)
        if "primary_node" in build_info:
            return

        sources = cast(list[Node], build_info.get("sources", []))

        env: Environment | None = None
        if target:
            env = target._env
        elif project:
            env = self._find_env_for_node(node, project)

        rule_name, _command = self._resolve_rule_key(node, build_info, target, env)

        # Handle multi-output builds from generic commands
        all_targets = build_info.get("all_targets")
        outputs_info = build_info.get("outputs")

        if all_targets and len(cast(list[Node], all_targets)) > 1:
            # Generic command with multiple outputs
            target_nodes = cast(list[FileNode], all_targets)
            output = " ".join(self._output_ref(t) for t in target_nodes)
        elif outputs_info:
            # Multi-output build (from MultiOutputBuilder)
            explicit_outputs: list[str] = []
            implicit_outputs: list[str] = []

            for _name, info in outputs_info.items():
                path = self._escape_output_path(info["path"])
                if info.get("implicit", False):
                    implicit_outputs.append(path)
                else:
                    explicit_outputs.append(path)

            output = " ".join(explicit_outputs)
            if implicit_outputs:
                output += " | " + " ".join(implicit_outputs)
        else:
            # Single-output build
            output = self._output_ref(node)

        # Explicit dependencies (sources + library dependencies)
        def get_dep_path(s: FileNode) -> str:
            if getattr(s, "role", None) == "install_output":
                return self._install_output_ref(s)

            # Build outputs are relative to the build dir
            if getattr(s, "_build_info", None) is not None or s.is_target:
                return self._escape_output_path(s.path)

            # Files inside the build dir are build artifacts even without
            # _build_info (e.g., dyndep files written during after_resolve);
            # they must match the build-relative path used elsewhere.
            if self._is_under_build_dir(s.path):
                return self._escape_output_path(s.path)

            # Source file: reference via $topdir when under the project root
            rel = self._make_source_relative(s.path)
            if rel is not None:
                return "$topdir/" + self._escape_path(rel)

            # External file: escape as-is
            return self._escape_path(s.path)

        # Start with sources from build_info
        explicit_deps_list = [
            get_dep_path(s) for s in sources if isinstance(s, FileNode)
        ]

        # Add any additional explicit deps (e.g., libraries for linking)
        # that aren't already in sources
        source_paths_set = {s.path for s in sources if isinstance(s, FileNode)}
        for dep in node.explicit_deps:
            if isinstance(dep, FileNode) and dep.path not in source_paths_set:
                explicit_deps_list.append(self._output_ref(dep))

        explicit_deps = " ".join(explicit_deps_list)

        # Implicit dependencies (from node.implicit_deps)
        implicit_deps = ""
        if node.implicit_deps:
            implicit = " ".join(
                get_dep_path(d) for d in node.implicit_deps if isinstance(d, FileNode)
            )
            if implicit:
                implicit_deps = f" | {implicit}"

        # Order-only dependencies (Ninja's `||`): must exist before this edge
        # runs, but changing one does not make it dirty. A dep that is already
        # explicit or implicit is stronger, so it never repeats here.
        order_only = ""
        if node.order_only_deps:
            stronger = {
                d.path
                for d in (*node.explicit_deps, *node.implicit_deps)
                if isinstance(d, FileNode)
            }
            ordered = " ".join(
                get_dep_path(d)
                for d in node.order_only_deps
                if isinstance(d, FileNode) and d.path not in stronger
            )
            if ordered:
                order_only = f" || {ordered}"

        f.write(
            f"build {output}: {rule_name} {explicit_deps}{implicit_deps}{order_only}\n"
        )

        # Dyndep attribute for module dependencies
        dyndep = build_info.get("dyndep")
        if dyndep:
            f.write(f"  dyndep = {self._escape_path(str(dyndep))}\n")

        self._write_build_variables(f, node, target, build_info, project)

    def _write_build_variables(
        self,
        f: TextIO,
        node: FileNode,
        target: Target | None,
        build_info: dict[str, object],
        project: Project | None = None,
    ) -> None:
        """Write per-build variables for a build statement.

        $in/$out are never written — ninja sets them from the build
        statement. Multi-output builds get out_<name> variables; generic
        commands get source_N/target_N for indexed access.

        An edge with a ``cwd`` writes those paths as seen from there: they
        exist only to be read by that edge's command, which runs there.
        """
        sources = cast(list[Node], build_info.get("sources", []))
        cwd = cast("Path | None", build_info.get("cwd"))

        def is_build_output(s: FileNode) -> bool:
            return getattr(s, "_build_info", None) is not None or s.is_target

        def get_source_path(s: FileNode) -> str:
            if cwd is not None:
                return self._path_at(s.path, cwd, output=is_build_output(s))

            if is_build_output(s):
                return self._make_output_relative(s.path)

            rel = self._make_source_relative(s.path)
            if rel is not None:
                return f"$topdir/{rel}"

            return str(s.path)

        def get_target_path(node: FileNode) -> str:
            if cwd is None:
                return self._output_command_path(node)
            return self._path_at(node.path, cwd, output=True)

        source_file_nodes = [s for s in sources if isinstance(s, FileNode)]

        all_targets = build_info.get("all_targets")
        if all_targets:
            for i, src in enumerate(source_file_nodes):
                path = self._escape_ninja_value(get_source_path(src))
                f.write(f"  source_{i} = {path}\n")
            target_nodes = cast(list[FileNode], all_targets)
            for i, tgt in enumerate(target_nodes):
                path = self._escape_ninja_value(get_target_path(tgt))
                f.write(f"  target_{i} = {path}\n")

        outputs_info = build_info.get("outputs")
        if outputs_info and isinstance(outputs_info, dict):
            for i, (name, info) in enumerate(outputs_info.items()):
                if isinstance(info, dict):
                    info_dict = cast(dict[str, Any], info)
                    out_path = self._escape_ninja_value(
                        self._make_output_relative(info_dict["path"])
                    )
                    f.write(f"  out_{name} = {out_path}\n")
                    # target_N supports TargetPath(index=N) in commands
                    f.write(f"  target_{i} = {out_path}\n")

        # $out_basename, for a TargetPath(basename=True) in the command. Only
        # when one is present: emitting it for every edge would add a line per
        # compile for the benefit of the few links that name it.
        if self._wants_out_basename(build_info):
            f.write(
                f"  out_basename = {self._escape_for_ninja_variable(node.path.name)}\n"
            )

        # Per-node values the toolchain attached (MODULE_NAME, QMLURI, ...).
        # They live here rather than in the rule so one rule serves every node
        # built from the same template.
        node_vars = build_info.get("vars")
        if node_vars and isinstance(node_vars, dict):
            for name, value in cast("dict[str, object]", node_vars).items():
                self._check_node_var_name(name, node)
                f.write(f"  {name} = {self._render_node_var(value, cwd)}\n")

        # Custom per-build variables from build_info (legacy support)
        custom_vars = build_info.get("variables")
        if custom_vars and isinstance(custom_vars, dict):
            for var_name, var_value in custom_vars.items():
                if var_value:  # Only write non-empty values
                    escaped_value = self._escape_for_ninja_variable(str(var_value))
                    f.write(f"  {var_name} = {escaped_value}\n")

    #: Names the generator defines itself; a per-node variable may not shadow
    #: one, or the edge's own paths would be rewritten by its value.
    _RESERVED_VARS = frozenset({"in", "out", "topdir", "out_basename"})

    @classmethod
    def _check_node_var_name(cls, name: str, node: FileNode) -> None:
        if name in cls._RESERVED_VARS or re.fullmatch(r"(source|target)_\d+", name):
            raise ValueError(
                f"Per-node variable {name!r} on {node.path} shadows one the "
                f"generator defines. Pick another name: ninja would use this "
                f"value where the edge's own paths belong."
            )

    def _render_node_var(self, value: object, cwd: Path | None) -> str:
        """One per-node value as ninja variable text.

        The same shapes a command carries — a plain string, a PathToken, or a
        list of either — so it goes through the same relativization and
        quoting the command tokens do.
        """
        from pcons.core.subst import to_shell_command

        tokens = value if isinstance(value, list) else [value]
        return to_shell_command(
            self._relativize_command_tokens(cast("list[str]", tokens), cwd=cwd),
            shell="ninja",
        )

    @staticmethod
    def _wants_out_basename(build_info: dict[str, object]) -> bool:
        """Whether this edge's command names ``$out_basename``."""
        from pcons.core.subst import TargetPath

        command = build_info.get("command")
        if not isinstance(command, list):
            return False
        return any(
            isinstance(token, TargetPath) and token.basename for token in command
        )

    def _write_regen(self, f: TextIO, project: Project, ninja_file: Path) -> None:
        """Write the self-regeneration edge (``generator = 1``).

        Ninja brings its own manifest up to date before running anything else,
        and re-reads it if it changed — so editing the build script, or any
        file the build description read, re-runs pcons automatically. Those
        inputs may themselves be build outputs, which is what makes staged
        generation work (see ``Project.generated_input``).
        """
        from pcons.core import invocation
        from pcons.core.subst import to_shell_command

        deps = project.configure_dependencies
        if not deps:
            return

        inv = invocation.current()
        if inv is None:
            trace("generate", "No recorded invocation; skipping regen rule")
            return
        argv = inv.command(root_dir=project.root_dir, run_dir=ninja_file.parent)
        if argv is None:
            trace("generate", "Invocation not reconstructable; skipping regen rule")
            return

        manifest = self._escape_output_path(ninja_file)
        dep_refs = " ".join(sorted(self._manifest_dep_ref(d) for d in deps))

        f.write("# Re-run pcons when the build description changes\n")
        f.write("rule pcons_regen\n")
        f.write(f"  command = {to_shell_command(argv, shell='ninja')}\n")
        f.write("  description = Regenerating $out\n")
        f.write("  generator = 1\n")
        f.write("  pool = console\n")
        f.write(f"build {manifest}: pcons_regen | {dep_refs}\n")
        f.write("\n")

    def _manifest_dep_ref(self, path: Path) -> str:
        """Render a configure dependency for the regen edge.

        Build-tree inputs must match how their producing edge names them
        (relative to the build dir); source-tree inputs are referenced through
        ``$topdir`` like any other source.
        """
        if self._is_under_build_dir(path):
            return self._escape_output_path(path)
        rel = self._make_source_relative(path)
        if rel is not None:
            return "$topdir/" + self._escape_path(rel)
        return self._escape_path(path)

    def _write_aliases(self, f: TextIO, project: Project) -> None:
        """Write phony rules for aliases, merged across the project tree."""
        aliases = project.tree_aliases
        if not aliases:
            return

        f.write("# Aliases\n")
        for name, nodes in aliases.items():
            members: list[str] = []
            for t in nodes:
                if isinstance(t, AliasNode):
                    # An alias may group other aliases: a phony rule can name
                    # another phony target directly. Alias() rejects cycles.
                    members.append(t.alias_name)
                elif isinstance(t, FileNode):
                    members.append(self._output_ref(t))
            if members:
                f.write(f"build {name}: phony {' '.join(members)}\n")
        f.write("\n")

    def _write_tests(self, f: TextIO, project: Project) -> None:
        """Write ``test-build`` (compile tests) and ``test`` (run them) phonies.

        Emits nothing if the project declared no tests. The runner is invoked
        as ``python -m pcons.test_runner`` because the ``pcons`` script may
        not be on PATH (e.g. ``uvx pcons``).
        """
        test_targets = [t for t in project.targets if t.target_type == "test"]
        if not test_targets:
            return

        program_outputs: list[str] = []
        seen: set[str] = set()
        for test_target in test_targets:
            for dep in test_target.dependencies:
                for node in dep.output_nodes:
                    if isinstance(node, FileNode):
                        out = self._output_ref(node)
                        if out not in seen:
                            seen.add(out)
                            program_outputs.append(out)

        f.write("# Tests\n")
        if program_outputs:
            f.write(f"build test-build: phony {' '.join(program_outputs)}\n")
        else:
            f.write("build test-build: phony\n")

        # `pool = console` keeps runner output unbuffered and serial. Embed
        # the Python running pcons itself so the runner can import `pcons`.
        # Shell-quote (not just ninja $-escaping) so an interpreter path with
        # spaces survives: ninja unescapes "$ " to a bare space, which the
        # shell would split on.
        from pcons.core.subst import to_shell_command

        python_exe = to_shell_command(
            [sys.executable.replace("\\", "/")], shell="ninja"
        )
        f.write("rule pcons_test\n")
        f.write(
            f"  command = {python_exe} -m pcons.test_runner "
            "--manifest=tests.json --no-color\n"
        )
        f.write("  pool = console\n")
        f.write("  description = Running tests\n")
        f.write("build test: pcons_test | test-build\n")
        f.write("\n")

    def _write_defaults(self, f: TextIO, project: Project) -> None:
        """Write default targets and 'all' phony target."""
        f.write("# Default targets\n")
        user_defaults: list[str] = []
        all_outputs: list[str] = []

        # Collect user-specified default targets
        for target in project.default_targets:
            for out_node in target.output_nodes:
                if isinstance(out_node, FileNode):
                    user_defaults.append(self._output_ref(out_node))

        # Collect all target outputs for 'all' target (utility targets
        # with build_by_default=False are only built when requested).
        for target in project.targets:
            if not getattr(target, "build_by_default", True):
                continue
            for node in target.output_nodes:
                if isinstance(node, FileNode):
                    all_outputs.append(self._output_ref(node))

        if all_outputs:
            # Create 'all' phony target — builds every target in the project
            f.write(f"build all: phony {' '.join(all_outputs)}\n")

        # Collect programs and libraries for implicit default
        prog_lib_outputs: list[str] = []
        for target in project.targets:
            if not getattr(target, "build_by_default", True):
                continue
            if target.target_type in (
                "program",
                "shared_library",
                "static_library",
            ):
                for node in target.output_nodes:
                    if isinstance(node, FileNode):
                        prog_lib_outputs.append(self._escape_output_path(node.path))

        # Set default: user-specified targets, or programs & libraries
        if user_defaults:
            f.write(f"default {' '.join(user_defaults)}\n")
        elif prog_lib_outputs:
            f.write(f"default {' '.join(prog_lib_outputs)}\n")
        elif all_outputs:
            f.write("default all\n")

    def _escape_path(self, path: Path | str) -> str:
        """Escape a path for use in Ninja files.

        Ninja requires escaping of $, :, and whitespace.
        Always uses forward slashes for cross-platform compatibility.
        """
        path_str = str(path)
        # Normalize to forward slashes (Ninja handles them on all platforms)
        path_str = path_str.replace("\\", "/")
        # Escape special characters
        return self.ESCAPE_CHARS.sub(r"$\1", path_str)

    def _make_output_relative(self, path: Path | str) -> str:
        """Make an output path relative to the build dir, where ninja runs
        (contract: pcons.core.paths.execution_relative)."""
        if self._path_resolver is not None:
            return self._path_resolver.make_execution_relative(path)
        # Resolver-less project (tests with bare stubs)
        from pcons.core.paths import execution_relative

        return execution_relative(
            path,
            execution_dir=self._output_dir,
            build_dir_parts=self._build_dir_parts or (),
        )

    def _escape_output_path(self, path: Path | str) -> str:
        """Make an output path relative to build dir and escape for Ninja."""
        return self._escape_path(self._make_output_relative(path))

    def _install_output_ref(self, node: FileNode) -> str:
        """Render an install-output node (``role == "install_output"``).

        Such nodes live outside the build dir (e.g. ``<root>/dist/bin/app``).
        They are emitted like source files (``$topdir/...``) when under the
        project root, otherwise absolute.
        """
        rel = self._make_source_relative(node.path)
        if rel is not None:
            return "$topdir/" + self._escape_path(rel)
        return self._escape_path(node.path)

    def _output_command_path(self, node: FileNode) -> str:
        """An output as the command must name it, honouring its role.

        The build statement says ``$topdir/outdir/copy.txt`` for a destination
        outside the build tree, so a ``$target_N`` naming the same file has to
        agree — pointing them at different places leaves the edge dirty after
        every run, or writes the wrong file.
        """
        if getattr(node, "role", None) == "install_output":
            rel = self._make_source_relative(node.path)
            return f"$topdir/{rel}" if rel is not None else str(node.path)
        return self._make_output_relative(node.path)

    def _output_ref(self, node: FileNode) -> str:
        """Render an output-node reference.

        Build outputs are relative to the build dir.
        For install outputs see _install_output_ref().
        """
        if getattr(node, "role", None) == "install_output":
            return self._install_output_ref(node)
        return self._escape_output_path(node.path)

    def _make_source_relative(self, path: Path | str) -> str | None:
        """Make a source path relative to the project root, or None if it
        can't be (outside project, or different drive on Windows).

        The caller prepends $topdir if needed.
        """
        if self._path_resolver is not None:
            path_obj = Path(path)
            if not path_obj.is_absolute() and self._project_root is not None:
                path_obj = self._project_root / path_obj
            result = self._path_resolver.make_project_relative(path_obj.resolve())
            # An absolute result means it couldn't be made relative
            if Path(result).is_absolute():
                return None
            return result

        # Fallback for tests without full project context
        if self._project_root is None or self._output_dir is None:
            return None

        path_obj = Path(path)
        if not path_obj.is_absolute():
            path_obj = self._project_root / path_obj
        path_obj = path_obj.resolve()

        try:
            rel_to_root = path_obj.relative_to(self._project_root)
            return str(rel_to_root).replace("\\", "/")
        except ValueError:
            return None

    def _is_build_dir_path(self, path: str) -> bool:
        """Check if a path resolves to the build directory itself."""
        if self._output_dir is None:
            return False
        path_obj = Path(path)
        if not path_obj.is_absolute():
            if self._project_root:
                path_obj = self._project_root / path_obj
        try:
            return path_obj.resolve() == self._output_dir
        except (OSError, ValueError):
            return False

    def _is_under_build_dir(self, path: Path | str) -> bool:
        """Check if a path is inside (or is) the build directory."""
        if self._output_dir is None:
            return False
        path_obj = Path(path)
        if path_obj.is_absolute():
            try:
                path_obj.relative_to(self._output_dir)
                return True
            except ValueError:
                return False
        if self._build_dir_parts:
            n = len(self._build_dir_parts)
            return path_obj.parts[:n] == self._build_dir_parts
        return False

    def _relativize_flag_with_path(
        self, token: str, prefix: str | None = None, *, cwd: Path | None = None
    ) -> str:
        """Relativize a path-carrying flag (``-I<path>``, ``/LIBPATH:<path>``)
        the same way as any other path in the command — $topdir form, "." for
        the build dir, or relative to the edge's *cwd*.

        With *prefix* given, *token* is the bare path argument of a flag that
        was spelled as two tokens (``-isystem`` ``<path>``); the prefix is used
        only to detect the MSVC ``/I.`` style and is not re-attached.

        Returns the token unchanged if it isn't a path flag, or if the path
        can't be made project-relative (it lives outside the tree).
        """
        if prefix is None:
            prefix = self._path_flag_prefix(token)
            if prefix is None:
                return token
            path = token[len(prefix) :]
            if not path:
                return token
            # "--sysroot=<path>": the "=" joins the flag to its argument and
            # is no part of the path. Left in, the path reads as relative and
            # comes back as "--sysroot../=/opt/sdk".
            if path.startswith("="):
                prefix += "="
                path = path[1:]
                if not path:
                    return token
        else:
            path = token
            prefix = ""

        # Outside the project tree (an SDK, a system prefix), the path comes
        # back absolute — the only thing it can be.
        return f"{prefix}{self._relativize_path_for_ninja(path, cwd)}"

    def _path_flag_prefix(self, token: str) -> str | None:
        """The path-flag prefix *token* starts with, if any.

        Longest match wins, so ``/external:I`` isn't mistaken for a token that
        merely starts with ``/e``.
        """
        matches = [p for p in self._path_flags if token.startswith(p)]
        if not matches:
            return None
        return max(matches, key=len)

    def _warn_build_dir_in_command(self, token: str) -> None:
        """Warn once about a build-dir-relative path written into a command.

        A command runs *in* the build directory, while ``project.build_dir``
        is relative to the project *root* — so interpolating it names a
        directory one level too deep: ``build/tool`` looks for
        ``build/build/tool`` at run time. Nothing checks it; a tool that only
        reads the path finds nothing and carries on.

        The spellings that work are ``$SRCDIR/...`` for a source-tree file, a
        marker or ``PathToken`` for something this build produces, or
        ``cwd=`` to move the whole command — so an edge that names a ``cwd``
        is left alone, since there the frame is explicit and deliberate.

        A path really is build-dir-relative once in a while (a directory named
        ``build`` *inside* the build directory). Set the build variable
        ``PCONS_WARN_BUILD_DIR_PATHS=0`` to silence this.
        """
        if not self._build_dir_parts or token in self._warned_build_dir_paths:
            return
        from pcons.core.errors import ConfigureError
        from pcons.core.vars import get_var

        try:
            warn = get_var("PCONS_WARN_BUILD_DIR_PATHS", True)
        except ConfigureError:
            # A switch that silences a warning must not be able to fail
            # generation, so an unreadable value just leaves the warning on.
            warn = True
        if not warn:
            return
        build_dir = "/".join(self._build_dir_parts)
        # Only where a path can start: the token itself, or after a separator
        # like "-Wl," or "--out=". Not after a "/", which is already anchored.
        if not re.search(rf"(?:^|[=,:\s]){re.escape(build_dir)}/", token):
            return
        self._warned_build_dir_paths.add(token)
        logger.warning(
            "Command token names a path under %r, but a command runs *in* the "
            "build directory, so this resolves to %s/%s/...:\n  %s\n"
            "  Use $SRCDIR/... for a source file, a PathToken for something "
            "this build produces, or cwd= to move the command. Set "
            "PCONS_WARN_BUILD_DIR_PATHS=0 if the path is right as written.",
            build_dir,
            build_dir,
            build_dir,
            token,
        )

    def _warn_absolute_in_tree(self, flag: str) -> None:
        """Warn once per flag that carries an absolute path from inside the
        project tree.

        pcons rewrites the paths in flags it recognizes to ``$topdir/...`` so
        build.ninja stays relocatable and shareable between checkouts. A path
        it couldn't see through — a flag spelling we don't know, or one
        assembled by hand — silently defeats that, and silence is the real
        problem. Paths outside the tree (SDKs, system prefixes) are fine and
        stay quiet.
        """
        if self._project_root is None:
            return
        if str(self._project_root) not in flag:
            return
        if flag in self._warned_absolute_paths:
            return
        self._warned_absolute_paths.add(flag)
        logger.warning(
            "Flag carries an absolute path inside the project tree, so "
            "build.ninja is not relocatable:\n  %s\n"
            "  pcons rewrites paths in the flags it knows (%s). For anything "
            "else, use the tool's includes/libdirs lists or a PathToken.",
            flag,
            ", ".join(sorted(self._path_flags)) or "none configured",
        )

    def _relativize_command_tokens(
        self,
        tokens: list[str] | list[CommandToken],
        *,
        source_count: int = 0,
        target_count: int = 0,
        cwd: Path | None = None,
    ) -> list[str]:
        """Relativize command tokens for ninja execution.

        SourcePath/TargetPath markers become $in/$out (or $source_N/$target_N
        in indexed mode), PathTokens are relativized, and plain strings fall
        back to pattern-based path-flag detection.

        A slice marker (``${SOURCES[2:]}``) expands to the indexed references
        it covers, which is why the counts are needed: ninja has no way to
        say "the rest of the inputs".

        With *cwd*, every path is rendered as seen from there instead of from
        the build directory. $in/$out can't be: they are ninja's own view of
        the edge, which has to stay build-relative for dependency tracking.
        So a cwd edge uses the per-edge $source_N/$target_N variables, which
        the build statement writes relative to the same directory.
        """
        from pcons.core.subst import PathToken, SourcePath, TargetPath

        # An explicit index on any marker (even 0) switches all markers of
        # that type to indexed mode; index=None means "auto" ($in/$out).
        # A slice does the same: it renders as indexed references.
        has_indexed_source = any(
            isinstance(t, SourcePath) and (t.index is not None or t.is_slice)
            for t in tokens
        )
        has_indexed_target = any(
            isinstance(t, TargetPath) and (t.index is not None or t.is_slice)
            for t in tokens
        )

        result: list[str] = []
        expect_path = False
        for token in tokens:
            if expect_path:
                # Argument of a path flag spelled as two tokens ("-isystem",
                # "/abs/path"): relativize it as the bare path it is. Only
                # when absolute — a relative argument may not be a path at
                # all, and rewriting it would change its meaning.
                expect_path = False
                if isinstance(token, str) and Path(token).is_absolute():
                    result.append(
                        self._relativize_flag_with_path(token, prefix="", cwd=cwd)
                    )
                    continue
            if isinstance(token, SourcePath):
                if token.is_slice:
                    result.extend(self._slice_refs(token, "source", source_count))
                    continue
                if token.index is None and cwd is not None:
                    # $in has no cwd-relative spelling; name the inputs one by
                    # one instead, which is what an unbounded slice does.
                    result.extend(self._slice_refs(token, "source", source_count))
                    continue
                if token.index is not None or has_indexed_source:
                    ninja_var = f"$source_{token.index or 0}"
                else:
                    ninja_var = "$in"
                result.append(f"{token.prefix}{ninja_var}{token.suffix}")
            elif isinstance(token, TargetPath):
                if token.basename:
                    # A per-edge variable, so the rule text is the same for
                    # every target and they share one rule. Deliberately not
                    # $target_N: an index here would flip has_indexed_target
                    # and rewrite this command's other markers with it.
                    result.append(f"{token.prefix}$out_basename{token.suffix}")
                    continue
                if token.is_slice:
                    result.extend(self._slice_refs(token, "target", target_count))
                    continue
                if token.index is None and cwd is not None:
                    result.extend(self._slice_refs(token, "target", target_count))
                    continue
                if token.index is not None or has_indexed_target:
                    ninja_var = f"$target_{token.index or 0}"
                else:
                    ninja_var = "$out"
                result.append(f"{token.prefix}{ninja_var}{token.suffix}")
            elif isinstance(token, NodeVar):
                # The value goes on the build statement, so the rule text is
                # the same for every node that uses this template.
                result.append(f"${token.name}")
            elif isinstance(token, PathToken):
                result.append(
                    token.relativize(lambda p: self._relativize_path_for_ninja(p, cwd))
                )
            else:
                s = str(token)
                if "$SRCDIR" in s:
                    # $SRCDIR and $topdir both mean the project source root.
                    # The token is explicitly rooted, so it skips the path
                    # relativization below — which would treat the literal
                    # "$topdir" as a path component and root it a second
                    # time ("-I$topdir/$topdir/...").
                    srcdir = (
                        "$topdir"
                        if cwd is None or self._project_root is None
                        else self._path_at(self._project_root, cwd)
                    )
                    result.append(s.replace("$SRCDIR", srcdir))
                    continue
                # A bare path flag takes its path as the next token
                expect_path = s in self._path_flags
                relativized = self._relativize_flag_with_path(s, cwd=cwd)
                if relativized.startswith("-"):
                    self._warn_absolute_in_tree(relativized)
                if cwd is None:
                    self._warn_build_dir_in_command(relativized)
                result.append(relativized)
        return result

    @staticmethod
    def _slice_refs(token: Any, kind: str, count: int) -> list[str]:
        """The indexed references a marker covers, one token each.

        Ninja has no "rest of the inputs" variable, so a slice is written out
        as ``$source_2 $source_3 ...`` for this edge's actual count. Edges
        with different counts therefore get different rules; that is fine for
        the code-generation commands slices exist for. An unindexed marker has
        no range at all, so this spells out every reference — which is what a
        cwd edge needs in place of ``$in``/``$out``.
        """
        start, stop, _ = slice(token.start, token.stop).indices(count)
        return [f"{token.prefix}${kind}_{i}{token.suffix}" for i in range(start, stop)]

    def _relativize_path_for_ninja(self, path: str, cwd: Path | None = None) -> str:
        """Transform a path for ninja execution: $topdir/... for project
        paths, "." for the build dir, unchanged for external paths.

        An edge with a *cwd* runs somewhere else, so its paths are written
        relative to that directory instead.
        """
        if cwd is not None:
            return self._path_at(path, cwd)

        if self._is_build_dir_path(path):
            return "."

        # A path inside the build dir is where the command already runs;
        # $topdir would only route it out of the tree and back in.
        rel_build = self._make_build_relative(path)
        if rel_build is not None:
            return rel_build

        rel = self._make_source_relative(path)
        if rel is not None:
            return f"$topdir/{rel}"

        return path

    def _make_build_relative(self, path: Path | str) -> str | None:
        """The path as seen from the build directory, or None if it isn't
        inside it. Mirrors get_dep_path's treatment of build-dir files."""
        path_obj = Path(path)
        if path_obj.is_absolute():
            if self._output_dir is None:
                return None
            try:
                rel = path_obj.resolve().relative_to(self._output_dir)
            except (OSError, ValueError):
                return None
            return str(rel).replace("\\", "/")
        if not self._is_under_build_dir(path_obj):
            return None
        parts = path_obj.parts[len(self._build_dir_parts) :]
        return "/".join(parts) if parts else "."

    def _escape_ninja_value(self, token: str) -> str:
        """Escape a token for a Ninja variable value, separators untouched.

        Ninja escaping (space -> $ , colon -> $:, dollar -> $$) works
        consistently across platforms, unlike shell quoting; $topdir
        references are preserved.

        Path separators are left exactly as they came. A value like
        ``target_0`` is read back by the edge's own command, and cmd.exe
        will not run a program whose path uses forward slashes -- it
        reads the first one as the start of a switch.
        """
        # Shield $topdir from the $$ escaping below
        token = token.replace("$topdir", "\x00TOPDIR\x00")

        token = token.replace("$", "$$")
        token = token.replace(" ", "$ ")
        token = token.replace(":", "$:")

        # Restore $topdir
        return token.replace("\x00TOPDIR\x00", "$topdir")

    def _escape_for_ninja_variable(self, token: str) -> str:
        """Escape a token for a Ninja variable value, in ninja's own spelling.

        As :meth:`_escape_ninja_value`, and additionally normalizes
        backslashes to forward slashes -- for values ninja itself reads
        rather than ones handed to a command.
        """
        return self._escape_ninja_value(token.replace("\\", "/"))
