# SPDX-License-Identifier: MIT
"""An assembly source includes a header generated by a linked dependency.

The `.s` handler passes depfile=None, so ninja has no record of the include
other than the edge pcons writes.
"""

import sys

from pcons import Project

project = Project("order_only_generated_include")
env = project.Environment(toolchain=["gcc", "c"])

py = sys.executable.replace("\\", "/")
gen = env.Command(
    target=project.build_dir / "gen.inc",
    source=["src/gen.py"],
    command=[py, "${SOURCES[0]}", "$TARGET"],
    name="geninc",
)

helper = project.StaticLibrary("helper", env, sources=["src/helper.c"])
helper.link(gen)

app = project.Program("app", env, sources=["src/val.s", "src/main.c"])
app.link(helper)
