# SPDX-License-Identifier: MIT
"""Generate typed-stub mixin classes for pcons's dynamic-attribute classes.

Four classes use `__getattr__` for dispatch and lose static type checking:

  - `Project` → `core/_project_builder_stubs.py` (introspected from
    BuilderRegistry)
  - `Environment` → `core/_environment_stubs.py` (introspected from each
    toolchain's TOOL_NAMES plus Environment.STANDALONE_TOOL_NAMES)
  - `ToolConfig` → `core/_toolconfig_stubs.py` (hand-maintained list here)
  - `UsageRequirements` → `core/_usage_requirements_stubs.py`
    (hand-maintained list here)

ToolConfig/UsageRequirements lists must be hand-maintained because their
variables aren't registered anywhere at runtime. The mixins are inherited
only under `TYPE_CHECKING`; a freshness test catches drift between the
generator output and the committed files.

Usage:
    python -m pcons._gen_stubs              # rewrite all stub files
    python -m pcons._gen_stubs --check      # exit 1 if any file is stale
    python -m pcons._gen_stubs --print      # write all to stdout
"""

from __future__ import annotations

import inspect
import sys
from collections.abc import Callable, Sequence
from inspect import Parameter
from pathlib import Path

import click

from pcons._cli_click import run_cli
from pcons.builders import register_builtin_builders
from pcons.core.builder_registry import BuilderRegistry


def _stub_targets() -> dict[str, Callable[[], str]]:
    """Map of relative path under pcons/ → function that produces the file content."""
    return {
        "core/_project_builder_stubs.py": generate_project_builder_stubs,
        "core/_environment_stubs.py": generate_environment_stubs,
        "core/_toolconfig_stubs.py": generate_toolconfig_stubs,
        "core/_usage_requirements_stubs.py": generate_usage_requirements_stubs,
        "core/_toolchain_names.py": generate_toolchain_names,
        "core/_preset_names.py": generate_preset_names,
    }


def _import_shipped_toolchains() -> None:
    """Import every shipped toolchain so its builders and tools register.

    Registration happens on import, so a generator that runs before anything
    has imported a toolchain sees an incomplete registry and silently drops
    its entries. Ordering must not decide the output, so every generator
    that reads a registry calls this first.

    The package is walked rather than listed, so a new toolchain module is
    picked up by existing; a hand-written list is one edit away from
    dropping a toolchain out of the generated stubs without saying so.
    """
    import importlib
    import pkgutil

    import pcons.contrib.latex.toolchain  # noqa: F401
    import pcons.toolchains

    for info in pkgutil.walk_packages(
        pcons.toolchains.__path__, prefix="pcons.toolchains."
    ):
        importlib.import_module(info.name)


def generate_toolchain_names() -> str:
    """Produce the full content of `core/_toolchain_names.py`."""
    _import_shipped_toolchains()
    from pcons.tools.toolchain import toolchain_registry

    lines = [
        "# SPDX-License-Identifier: MIT",
        "# ruff: noqa",
        "# fmt: off",
        '"""Known toolchain names accepted by `Environment(toolchain=...)`.',
        "",
        "GENERATED by `python -m pcons._gen_stubs`. Do not edit by hand.",
        "",
        "Scraped from the toolchain registry: finder names (auto-detection",
        'entry points like "c") and toolchain aliases (specific toolchains',
        'like "gcc"). The Literal exists purely for IDE completion and typo',
        "checking; plain `str` is also accepted at runtime so user-registered",
        'toolchains resolve normally."""',
        "",
        "from typing import Literal",
        "",
        "KnownToolchain = Literal[",
    ]
    for name, description in toolchain_registry.known_names().items():
        comment = f"  # {description}" if description else ""
        lines.append(f'    "{name}",{comment}')
    lines += ["]", ""]
    return "\n".join(lines)


def generate_preset_names() -> str:
    """Produce the full content of `core/_preset_names.py`."""
    _import_shipped_toolchains()
    from pcons.tools.toolchain import BaseToolchain

    # preset name → toolchain class names that declare it. Only classes with
    # TOOL_NAMES count (real toolchains, matching the environment stubs).
    sources: dict[str, set[str]] = {}

    def walk(cls: type) -> None:
        for sub in cls.__subclasses__():
            walk(sub)
            if getattr(sub, "TOOL_NAMES", ()):
                for name in getattr(sub, "FEATURE_PRESETS", {}):
                    sources.setdefault(name, set()).add(sub.__name__)

    walk(BaseToolchain)

    lines = [
        "# SPDX-License-Identifier: MIT",
        "# ruff: noqa",
        "# fmt: off",
        '"""Built-in feature preset names accepted by `env.apply_preset(...)`.',
        "",
        "GENERATED by `python -m pcons._gen_stubs`. Do not edit by hand.",
        "",
        "Scraped from every toolchain's FEATURE_PRESETS. The Literal exists",
        "purely for IDE completion and typo checking; plain `str` is also",
        "accepted at runtime so contributed presets ('scope/name') resolve",
        "normally. A name here may still be unavailable on a given system or",
        'toolchain — guard optional features with `env.has_preset(name)`."""',
        "",
        "from typing import Literal",
        "",
        "KnownFeaturePreset = Literal[",
    ]
    for name, srcs in sorted(sources.items()):
        lines.append(f'    "{name}",  # {", ".join(sorted(srcs))}')
    lines += ["]", ""]
    return "\n".join(lines)


# Annotation names that need rewriting because `Environment` is conventionally
# imported as `Env` in pcons code (and we want the stub to match).
_ANNOTATION_ALIASES = {"Environment": "Env"}

# Parameters dropped from generated stubs (auto-captured at the call site).
_DROPPED_PARAMS = {"defined_at"}


def _rewrite_annotation(anno: str) -> str:
    """Rewrite a string annotation to match the stub file's local names."""
    import re

    out = anno
    for src, dst in _ANNOTATION_ALIASES.items():
        out = re.sub(rf"\b{re.escape(src)}\b", dst, out)
    return out


def _format_param(p: Parameter) -> str:
    """Render a Parameter to its source-level spelling."""
    if p.kind is Parameter.VAR_POSITIONAL:
        return f"*{p.name}"
    if p.kind is Parameter.VAR_KEYWORD:
        return f"**{p.name}"

    parts = [p.name]
    if p.annotation is not Parameter.empty:
        parts.append(f": {_rewrite_annotation(str(p.annotation))}")
    if p.default is not Parameter.empty:
        parts.append(f" = {p.default!r}")
    return "".join(parts)


def _format_method(
    name: str, description: str, params: list[Parameter], ret: str
) -> str:
    """Format one typed method inside `class _ProjectBuilders` (8-space indent)."""
    lines: list[str] = []
    lines.append(f"        def {name}(")
    lines.append("            self,")

    saw_kw_only = False
    seen_positional = False
    for p in params:
        if p.kind in (Parameter.POSITIONAL_OR_KEYWORD, Parameter.POSITIONAL_ONLY):
            seen_positional = True
        if p.kind is Parameter.KEYWORD_ONLY and not saw_kw_only and seen_positional:
            lines.append("            *,")
            saw_kw_only = True
        if p.kind is Parameter.VAR_POSITIONAL:
            saw_kw_only = True
        lines.append(f"            {_format_param(p)},")

    lines.append(f"        ) -> {_rewrite_annotation(ret)}:")
    if description:
        lines.append(f'            """{description}"""')
    lines.append("            ...")
    return "\n".join(lines)


def _owner_of(create_target_fn: object) -> type | None:
    """Return the class that owns `create_target` if there is one.

    `@builder` is applied to a class with `create_target` as a staticmethod;
    in that case we recover the class for its docstring. Builders registered
    directly via `BuilderRegistry.register(create_target=<plain function>)`
    have no owning class, so we return None and let the caller fall back.
    """
    qualname = getattr(create_target_fn, "__qualname__", "")
    module = getattr(create_target_fn, "__module__", "")
    if "." in qualname and module:
        cls_name = qualname.rsplit(".", 1)[0]
        mod = sys.modules.get(module)
        if mod is not None:
            cls = getattr(mod, cls_name, None)
            if isinstance(cls, type):
                return cls
    return None


_PROJECT_FILE_HEADER = '''\
# SPDX-License-Identifier: MIT
# ruff: noqa
# fmt: off
"""Typed stub declarations for Project's built-in builder methods.

GENERATED by `python -m pcons._gen_stubs` from the BuilderRegistry. Do
not edit by hand — re-run the generator instead.

`Project` inherits from `_ProjectBuilders` only under TYPE_CHECKING (see
project.py). At runtime, `_ProjectBuilders = object` and builder lookup
falls through to `Project.__getattr__` as before. The methods here exist
solely so that type checkers (ty, pyright, mypy) can flag typos like
`project.Programx(...)` and provide completion. User-registered
`@builder` targets are not in this file; because Project's `__getattr__`
is hidden from type checkers, calls to them appear as unresolved
attributes and require a `type: ignore` / `ty: ignore` at the call site.
See examples/15_custom_builder for the canonical pattern.

The class body is nested under `if TYPE_CHECKING:` so that ty does not
treat the `def Foo(...) -> Target: ...` empty bodies as runtime errors;
type checkers see the declarations, runtime never executes them.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pcons.core.environment import Environment as Env
    from pcons.core.node import FileNode, Node
    from pcons.core.target import Target
    from pcons.tools.archive import ArchiveTarget

    class _ProjectBuilders:
        """Typed builder methods for Project (TYPE_CHECKING-only mixin)."""

'''


def generate_project_builder_stubs() -> str:
    """Produce the full content of `_project_builder_stubs.py`."""
    _import_shipped_toolchains()
    register_builtin_builders()
    parts: list[str] = [_PROJECT_FILE_HEADER]

    methods: list[str] = []
    for name, reg in sorted(BuilderRegistry.all().items()):
        sig = inspect.signature(reg.create_target)
        params = list(sig.parameters.values())[1:]  # drop leading `project`
        params = [p for p in params if p.name not in _DROPPED_PARAMS]
        ret = str(sig.return_annotation)

        description = ""
        owner = _owner_of(reg.create_target)
        if owner is not None and owner.__doc__:
            description = owner.__doc__.strip().splitlines()[0]
        if not description and reg.description:
            description = reg.description
        if reg.platforms:
            description = f"{description} [{'/'.join(reg.platforms)} only]".strip()

        methods.append(_format_method(name, description, params, ret))

    parts.append("\n\n".join(methods))
    parts.append("\n")
    return "".join(parts)


# Well-known Environment instance variables (initialized in Environment.__init__).
# Unlike tool namespaces, these are real attribute reads, not `_tools` lookups.
_ENVIRONMENT_VAR_TYPES: tuple[tuple[str, str], ...] = (
    ("build_dir", "Path"),
    ("variant", "str"),
    # Assignable from either spelling; stored as a Path.
    ("build_prefix", "str | Path | None"),
    ("runtime_directory", "str | Path | None"),
    ("library_directory", "str | Path | None"),
    ("archive_directory", "str | Path | None"),
)


def _collect_tool_names() -> list[tuple[str, str]]:
    """Walk every BaseToolchain subclass and union their TOOL_NAMES.

    Returns a sorted list of (tool_name, comma-joined-source-toolchain-names),
    including Environment's standalone tools.
    """
    _import_shipped_toolchains()
    from pcons.core.environment import Environment
    from pcons.tools.toolchain import BaseToolchain

    # tool name → set of toolchain class names that provide it
    sources: dict[str, set[str]] = {}

    def walk(cls: type) -> None:
        for sub in cls.__subclasses__():
            walk(sub)
            tools = getattr(sub, "TOOL_NAMES", ())
            for name in tools:
                sources.setdefault(name, set()).add(sub.__name__)

    walk(BaseToolchain)

    for name in Environment.STANDALONE_TOOL_NAMES:
        sources.setdefault(name, set()).add(
            "Environment._setup_standalone_tools (always)"
        )

    return [(name, ", ".join(sorted(srcs))) for name, srcs in sorted(sources.items())]


def _format_attribute_stubs_file(
    module_doc: str,
    extra_typecheck_imports: Sequence[str],
    class_name: str,
    class_doc: str,
    entries: Sequence[tuple[str, str, str | None]],  # name, type, optional comment
) -> str:
    """Format an attribute-stub file: header + class with
    `name: Type  # comment` lines (the method-less stub files)."""
    lines: list[str] = [
        "# SPDX-License-Identifier: MIT",
        "# ruff: noqa",
        "# fmt: off",
        f'"""{module_doc}"""',
        "",
        "from __future__ import annotations",
        "",
        "from pathlib import Path",
        "from typing import TYPE_CHECKING, Any",
        "",
        "if TYPE_CHECKING:",
    ]
    for imp in extra_typecheck_imports:
        lines.append(f"    {imp}")
    lines.extend(
        [
            "",
            f"    class {class_name}:",
            f'        """{class_doc}"""',
            "",
        ]
    )
    for name, typ, comment in entries:
        suffix = f"  # {comment}" if comment else ""
        lines.append(f"        {name}: {typ}{suffix}")
    lines.append("")
    return "\n".join(lines)


def generate_environment_stubs() -> str:
    """Produce the full content of `_environment_stubs.py`."""
    module_doc = (
        "Typed stub declarations for Environment's tool namespaces and known variables.\n"
        "\n"
        "GENERATED by `python -m pcons._gen_stubs`. Do not edit by hand.\n"
        "\n"
        "Tool namespaces come from two sources, both introspected at generation\n"
        "time:\n"
        "  - Each Toolchain subclass declares `TOOL_NAMES: ClassVar[tuple[...]]`.\n"
        "  - Environment declares `STANDALONE_TOOL_NAMES` for tools installed\n"
        "    by `_setup_standalone_tools()` regardless of toolchain.\n"
        "\n"
        "Adding a new tool to a toolchain therefore requires only updating that\n"
        "toolchain's TOOL_NAMES — the freshness test catches the drift.\n"
        "\n"
        "Environment.__getattr__ is intentionally left visible to type checkers\n"
        "(returning `Any`), so user-defined cross-tool variables like\n"
        "`env.my_flag = ...` continue to work without a type:ignore. Known names\n"
        "below are typed more specifically and take precedence.\n"
        "\n"
        "Soundness tradeoff: every tool namespace below is declared as present\n"
        "on every Environment, but at runtime `env.cuda` only resolves if a\n"
        "CudaToolchain (or similar) actually populated `_tools['cuda']`. A GCC\n"
        "env will type-check `env.cuda.flags = [...]` and then AttributeError\n"
        "at use. This is a deliberate completion-over-soundness choice: typing\n"
        "each name as `ToolConfig | None` would force null-checks on the\n"
        "common path where the user already knows which toolchain they\n"
        "configured. Treat the declared names as a superset of what any given\n"
        "Environment actually carries."
    )
    tool_entries = _collect_tool_names()
    entries: Sequence[tuple[str, str, str | None]] = [
        (tool, "ToolConfig", source) for tool, source in tool_entries
    ] + [(var, typ, None) for var, typ in _ENVIRONMENT_VAR_TYPES]
    return _format_attribute_stubs_file(
        module_doc=module_doc,
        extra_typecheck_imports=["from pcons.core.toolconfig import ToolConfig"],
        class_name="_EnvironmentStubs",
        class_doc="Typed mixin for Environment (TYPE_CHECKING-only).",
        entries=entries,
    )


# Well-known per-tool variable names commonly read or set as `env.<tool>.<var>`.
# Toolchains can invent their own; these cover the universal C/C++/link surface.
# Tuple shape: (name, type, comment). Comment may be None.
_TOOLCONFIG_VAR_TYPES: tuple[tuple[str, str, str | None], ...] = (
    ("cmd", "str | list[Any]", "command template (string or token list)"),
    ("flags", "list[Any]", "compile/link flags; can hold strings or subst tokens"),
    ("includes", "list[Path | str]", "include directories"),
    (
        "system_includes",
        "list[Path | str]",
        "include dirs whose warnings are suppressed",
    ),
    ("defines", "list[str]", "preprocessor defines, e.g. ['FOO=1']"),
    ("libs", "list[Any]", "library names or Target/subst-token entries"),
    ("libdirs", "list[Path | str]", "library search directories"),
    ("frameworks", "list[str]", "macOS frameworks"),
    ("frameworkdirs", "list[Path | str]", "macOS framework search dirs"),
    ("launcher", "list[Any]", "program to run in front of the command, e.g. ccache"),
    ("exe", "str", "path to the tool executable"),
    ("version", "str", "the tool's detected version"),
    ("depflags", "list[Any]", "flags that make the compiler emit a depfile"),
    ("objcmd", "str | list[Any]", "compile-to-object command template"),
    ("progcmd", "str | list[Any]", "link-a-program command template"),
    ("sharedcmd", "str | list[Any]", "link-a-shared-library command template"),
    ("libcmd", "str | list[Any]", "create-a-static-library command template"),
    # Flag prefixes, so a toolchain spells -I / /I (etc.) in one place.
    ("iprefix", "str", "include-dir flag prefix, e.g. '-I'"),
    ("isysprefix", "str", "system-include-dir flag prefix, e.g. '-isystem'"),
    ("dprefix", "str", "define flag prefix, e.g. '-D'"),
    ("lprefix", "str", "library-dir flag prefix, e.g. '-L'"),
    ("fprefix", "str", "framework flag prefix, e.g. '-framework'"),
    ("sprefix", "str", "framework-search-dir flag prefix, e.g. '-F'"),
)


def generate_toolconfig_stubs() -> str:
    """Produce the full content of `_toolconfig_stubs.py`."""
    module_doc = (
        "Typed stub declarations for ToolConfig's well-known variables.\n"
        "\n"
        "GENERATED by `python -m pcons._gen_stubs`. Do not edit by hand.\n"
        "\n"
        "Variables under a tool namespace (`env.cc.flags`, `env.link.libs`, …)\n"
        "are stored in a dict and accessed via __getattr__, which returns Any.\n"
        "The names below cover the universal C/C++/link surface so editors can\n"
        "type and complete the common operations. Toolchain-specific variables\n"
        "continue to work via __getattr__ — that path stays visible to type\n"
        "checkers so unusual names do not need `type: ignore`."
    )
    entries: list[tuple[str, str, str | None]] = list(_TOOLCONFIG_VAR_TYPES)
    return _format_attribute_stubs_file(
        module_doc=module_doc,
        extra_typecheck_imports=[],  # only needs Path, already in base imports
        class_name="_ToolConfigStubs",
        class_doc="Typed mixin for ToolConfig (TYPE_CHECKING-only).",
        entries=entries,
    )


# Well-known usage-requirement names on target.public / target.private.
# Toolchains can invent their own; these are the C/C++ conventional set.
_USAGE_REQUIREMENT_TYPES: tuple[tuple[str, str, str | None], ...] = (
    (
        "include_dirs",
        "MutableSequence[Path | str]",
        "directories added to dependents' include path",
    ),
    (
        "system_include_dirs",
        "MutableSequence[Path | str]",
        "like include_dirs, but marked as system headers (-isystem, /external:I) so their warnings are suppressed",
    ),
    (
        "compile_flags",
        "MutableSequence[str | PathToken]",
        "flags propagated to dependents (strings, or PathToken for embedded paths)",
    ),
    (
        "link_flags",
        "MutableSequence[str | PathToken]",
        "flags propagated to dependents (strings, or PathToken for embedded paths)",
    ),
    (
        "defines",
        "MutableSequence[str]",
        "preprocessor defines propagated to dependents",
    ),
    (
        "link_libs",
        "MutableSequence[str | Target]",
        "link deps: a Target brings its public usage requirements (headers etc.); a str is a raw link token; public re-exports, private does not",
    ),
    (
        "link_dirs",
        "MutableSequence[Path | str]",
        "library search directories (-L) propagated to dependents",
    ),
    (
        "frameworks",
        "MutableSequence[str]",
        "macOS frameworks propagated to dependents (-framework)",
    ),
    (
        "framework_dirs",
        "MutableSequence[Path | str]",
        "macOS framework search directories propagated to dependents (-F)",
    ),
)


def generate_usage_requirements_stubs() -> str:
    """Produce the full content of `_usage_requirements_stubs.py`."""
    module_doc = (
        "Typed stub declarations for UsageRequirements's well-known fields.\n"
        "\n"
        "GENERATED by `python -m pcons._gen_stubs`. Do not edit by hand.\n"
        "\n"
        "`target.public.*` and `target.private.*` access values through\n"
        "UsageRequirements.__getattr__, which returns `list` for any name.\n"
        "The names below are the C/C++ conventional set. Toolchains can\n"
        "invent any other names they need; those continue to work via\n"
        "__getattr__ (kept visible to type checkers)."
    )
    entries: list[tuple[str, str, str | None]] = list(_USAGE_REQUIREMENT_TYPES)
    return _format_attribute_stubs_file(
        module_doc=module_doc,
        extra_typecheck_imports=[
            "from typing import MutableSequence",
            "from pcons.core.subst import PathToken",
            "from pcons.core.target import Target",
        ],
        class_name="_UsageRequirementsStubs",
        class_doc="Typed mixin for UsageRequirements (TYPE_CHECKING-only).",
        entries=entries,
    )


def _stub_file_path(relpath: str) -> Path:
    return Path(__file__).resolve().parent / relpath


def write_or_check(mode: str) -> int:
    targets = _stub_targets()
    rc = 0
    for relpath, producer in targets.items():
        new_content = producer()
        if mode == "print":
            sys.stdout.write(f"# === {relpath} ===\n")
            sys.stdout.write(new_content)
            sys.stdout.write("\n")
            continue

        path = _stub_file_path(relpath)
        current = path.read_text(encoding="utf-8") if path.exists() else ""

        if mode == "check":
            if current != new_content:
                sys.stderr.write(
                    f"{path} is out of date with generated stubs.\n"
                    f"Run: python -m pcons._gen_stubs\n"
                )
                rc = 1
        elif mode == "write":
            if current != new_content:
                path.write_text(new_content, encoding="utf-8")
                print(f"Updated {path}")
            else:
                print(f"{path} is up to date.")
        else:
            raise ValueError(f"unknown mode: {mode}")
    return rc


@click.command(
    "pcons._gen_stubs", context_settings={"help_option_names": ["-h", "--help"]}
)
@click.option("--check", is_flag=True, help="Fail if file is stale")
# Named to_stdout because `print` as a parameter would shadow the builtin.
@click.option("--print", "to_stdout", is_flag=True, help="Print to stdout")
def cli_gen_stubs(check: bool, to_stdout: bool) -> int:
    """Regenerate the typed-stub mixins, or check the committed ones."""
    if check and to_stdout:
        raise click.UsageError("--check and --print are mutually exclusive")
    mode = "check" if check else "print" if to_stdout else "write"
    return write_or_check(mode)


def main(argv: list[str] | None = None) -> int:
    return run_cli(cli_gen_stubs, prog_name="python -m pcons._gen_stubs", argv=argv)


if __name__ == "__main__":
    sys.exit(main())
