# SPDX-License-Identifier: MIT
# ruff: noqa
# fmt: off
"""Typed stub declarations for Environment's tool namespaces and known variables.

GENERATED by `python -m pcons._gen_stubs`. Do not edit by hand.

Tool namespaces come from two sources, both introspected at generation
time:
  - Each Toolchain subclass declares `TOOL_NAMES: ClassVar[tuple[...]]`.
  - Environment declares `STANDALONE_TOOL_NAMES` for tools installed
    by `_setup_standalone_tools()` regardless of toolchain.

Adding a new tool to a toolchain therefore requires only updating that
toolchain's TOOL_NAMES — the freshness test catches the drift.

Environment.__getattr__ is intentionally left visible to type checkers
(returning `Any`), so user-defined cross-tool variables like
`env.my_flag = ...` continue to work without a type:ignore. Known names
below are typed more specifically and take precedence.

Soundness tradeoff: every tool namespace below is declared as present
on every Environment, but at runtime `env.cuda` only resolves if a
CudaToolchain (or similar) actually populated `_tools['cuda']`. A GCC
env will type-check `env.cuda.flags = [...]` and then AttributeError
at use. This is a deliberate completion-over-soundness choice: typing
each name as `ToolConfig | None` would force null-checks on the
common path where the user already knows which toolchain they
configured. Treat the declared names as a superset of what any given
Environment actually carries."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pcons.core.toolconfig import ToolConfig

    class _EnvironmentStubs:
        """Typed mixin for Environment (TYPE_CHECKING-only)."""

        ar: ToolConfig  # EmscriptenToolchain, GccToolchain, GfortranToolchain, LlvmToolchain, SwiftToolchain, WasiToolchain
        archive: ToolConfig  # Environment._setup_standalone_tools (always)
        cc: ToolConfig  # ClangClToolchain, EmscriptenToolchain, GccToolchain, LlvmToolchain, MsvcToolchain, WasiToolchain
        cuda: ToolConfig  # CudaToolchain
        cxx: ToolConfig  # ClangClToolchain, EmscriptenToolchain, GccToolchain, LlvmToolchain, MsvcToolchain, WasiToolchain
        cycc: ToolConfig  # CythonToolchain
        cylink: ToolConfig  # CythonToolchain
        cython: ToolConfig  # CythonToolchain
        fc: ToolConfig  # GfortranToolchain
        install: ToolConfig  # Environment._setup_standalone_tools (always)
        latex: ToolConfig  # LatexToolchain
        lib: ToolConfig  # ClangClToolchain, MsvcToolchain
        link: ToolConfig  # ClangClToolchain, EmscriptenToolchain, GccToolchain, GfortranToolchain, LlvmToolchain, MsvcToolchain, SwiftToolchain, WasiToolchain
        metal: ToolConfig  # LlvmToolchain
        ml: ToolConfig  # ClangClToolchain, MsvcToolchain
        qt: ToolConfig  # QtToolchain
        rc: ToolConfig  # ClangClToolchain, MsvcToolchain
        swiftc: ToolConfig  # SwiftToolchain
        build_dir: Path
        variant: str
        build_prefix: Path | None
        runtime_directory: Path | None
        library_directory: Path | None
        archive_directory: Path | None
