# SPDX-License-Identifier: MIT
# ruff: noqa
# fmt: off
"""Typed stub declarations for Project's built-in builder methods.

GENERATED by `python -m pcons._gen_stubs` from the BuilderRegistry. Do
not edit by hand — re-run the generator instead.

`Project` inherits from `_ProjectBuilders` only under TYPE_CHECKING (see
project.py). At runtime, `_ProjectBuilders = object` and builder lookup
falls through to `Project.__getattr__` as before. The methods here exist
solely so that type checkers (ty, pyright, mypy) can flag typos like
`project.Programx(...)` and provide completion. User-registered
`@builder` targets are not in this file; because Project's `__getattr__`
is hidden from type checkers, calls to them appear as unresolved
attributes and require a `type: ignore` / `ty: ignore` at the call site.
See examples/15_custom_builder for the canonical pattern.

The class body is nested under `if TYPE_CHECKING:` so that ty does not
treat the `def Foo(...) -> Target: ...` empty bodies as runtime errors;
type checkers see the declarations, runtime never executes them.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pcons.core.environment import Environment as Env
    from pcons.core.node import FileNode, Node
    from pcons.core.target import Target
    from pcons.tools.archive import ArchiveTarget

    class _ProjectBuilders:
        """Typed builder methods for Project (TYPE_CHECKING-only mixin)."""

        def Appx(
            self,
            env: Env,
            *,
            name: str,
            version: str,
            publisher: str,
            sources: Sequence[Target | FileNode | Path | str],
            output: str | Path | None = None,
            display_name: str | None = None,
            description: str | None = None,
            processor_architecture: str = 'x64',
        ) -> Target:
            """Create a Windows AppX package (legacy MSIX format) [win32 only]"""
            ...

        def CargoBuild(
            self,
            name: str,
            env: Env,
            *,
            manifest: str | Path,
            crate_type: str = 'staticlib',
            profile: str = 'release',
            features: Sequence[str] = (),
            generate_header: str | Path | None = None,
            target_triple: str | None = None,
            extra_args: Sequence[str] = (),
            cargo: str = 'cargo',
        ) -> Target:
            """Build a Rust crate via cargo and return it as an ImportedTarget."""
            ...

        def Command(
            self,
            name: str,
            env: Env,
            *,
            target: str | Path | list[str | Path],
            source: str | Path | list[str | Path] | None = None,
            command: str | list[str] = '',
            restat: bool = False,
            write_if_different: bool = False,
            cwd: str | Path | None = None,
            launcher: Sequence[str] | None = None,
            env_vars: Mapping[str, str] | None = None,
            worker: Any = None,
            depfile: str | None = None,
            deps_style: str | None = None,
        ) -> Target:
            """Create a custom command target."""
            ...

        def ComponentPkg(
            self,
            env: Env,
            *,
            identifier: str,
            version: str,
            sources: Sequence[Target | FileNode | Path | str],
            install_location: str = '/Applications',
            output: str | Path | None = None,
            scripts_dir: Path | None = None,
            component_plist: Path | None = None,
            ownership: str = 'recommended',
            sign_identity: str | None = None,
        ) -> Target:
            """Create a macOS component package using pkgbuild [darwin only]"""
            ...

        def Dmg(
            self,
            env: Env,
            *,
            name: str,
            sources: Sequence[Target | FileNode | Path | str],
            volume_name: str | None = None,
            output: str | Path | None = None,
            format: str = 'UDZO',
            applications_symlink: bool = True,
        ) -> Target:
            """Create a macOS .dmg disk image [darwin only]"""
            ...

        def FlatBundle(
            self,
            env: Env,
            plugin: Target,
            *,
            bundle_dir: Path | str,
            dlls: list[Target | Path | str] | None = None,
            resources: Sequence[Path | str] | None = None,
        ) -> Target:
            """Create a flat directory bundle (cross-platform)"""
            ...

        def HeaderOnlyLibrary(
            self,
            name: str,
            include_dirs: list[str | Path] | None = None,
        ) -> Target:
            """Create a header-only (interface) library target."""
            ...

        def Install(
            self,
            dest_dir: Path | str,
            sources: Sequence[Target | FileNode | Path | str],
            *,
            name: str | None = None,
            no_prefix: bool = False,
            mode: int | None = None,
        ) -> Target:
            """Install files to a destination directory."""
            ...

        def InstallAs(
            self,
            dest: Path | str,
            source: Target | FileNode | Path | str,
            *,
            name: str | None = None,
            no_prefix: bool = False,
            mode: int | None = None,
        ) -> Target:
            """Install a file to a specific destination path."""
            ...

        def InstallDir(
            self,
            dest_dir: Path | str,
            source: Target | FileNode | Path | str,
            *,
            name: str | None = None,
            no_prefix: bool = False,
        ) -> Target:
            """Install a directory tree to a destination."""
            ...

        def MacosBundle(
            self,
            env: Env,
            plugin: Target,
            *,
            bundle_dir: Path | str,
            info_plist: str | Path | None = None,
            pkginfo: str | bytes | None = None,
            resources: Sequence[Path | str] | None = None,
            arch_subdir: str | None = None,
        ) -> Target:
            """Create a macOS .bundle or .plugin structure [darwin only]"""
            ...

        def MetalLibrary(
            self,
            name: str,
            env: Env,
            sources: Sequence[str | Path | Node] | None = None,
            depends: Sequence[Target | Node | Path | str] | None = None,
        ) -> Target:
            """A .metallib built from .metal sources — the form an application loads. [darwin only]"""
            ...

        def Msix(
            self,
            env: Env,
            *,
            name: str,
            version: str,
            publisher: str,
            sources: Sequence[Target | FileNode | Path | str],
            executable: str | None = None,
            output: str | Path | None = None,
            display_name: str | None = None,
            description: str | None = None,
            processor_architecture: str = 'x64',
            sign_cert: Path | None = None,
            sign_password_env: str | None = None,
        ) -> Target:
            """Create a Windows MSIX package [win32 only]"""
            ...

        def ObjectLibrary(
            self,
            name: str,
            env: Env,
            sources: Sequence[str | Path | Node | Target] | None = None,
            depends: Sequence[Target | Node | Path | str] | None = None,
        ) -> Target:
            """Create an object library target (compiles but doesn't link)."""
            ...

        def Pkg(
            self,
            env: Env,
            *,
            name: str,
            version: str,
            identifier: str,
            sources: Sequence[Target | FileNode | Path | str],
            install_location: str = '/Applications',
            output: str | Path | None = None,
            title: str | None = None,
            welcome: Path | None = None,
            readme: Path | None = None,
            license: Path | None = None,
            conclusion: Path | None = None,
            background: Path | None = None,
            min_os_version: str | None = None,
            scripts_dir: Path | None = None,
            sign_identity: str | None = None,
        ) -> Target:
            """Create a macOS product archive (.pkg) installer [darwin only]"""
            ...

        def Program(
            self,
            name: str,
            env: Env,
            sources: Sequence[str | Path | Node | Target] | None = None,
            depends: Sequence[Target | Node | Path | str] | None = None,
        ) -> Target:
            """Create a program (executable) target."""
            ...

        def QtDeploy(
            self,
            name: str,
            env: Env,
            *,
            app: Target,
            bundle: str | Path | None = None,
            deploy_dir: str | Path | None = None,
            flags: Sequence[str] = (),
        ) -> Target:
            """`ninja deploy` utility target (see module docstring)."""
            ...

        def QtProgram(
            self,
            name: str,
            env: Env,
            sources: Sequence[str | Path | Node] | None = None,
            *,
            link: Sequence[Target] = (),
            automoc: bool = True,
            autouic: bool = True,
            autorcc: bool = True,
            no_moc: Sequence[str | Path] = (),
        ) -> Target:
            """A Program whose sources may include .ui/.qrc files and Q_OBJECT"""
            ...

        def QtQmlModule(
            self,
            name: str,
            env: Env,
            *,
            uri: str,
            version: str = '1.0',
            qml_files: Sequence[str | Path] = (),
            sources: Sequence[str | Path] = (),
            link: Sequence[Target] = (),
            no_moc: Sequence[str | Path] = (),
        ) -> Target:
            """Build a QML module as an object target (see module docstring)."""
            ...

        def QtResources(
            self,
            name: str,
            env: Env,
            *,
            files: Sequence[str | Path],
            prefix: str = '/',
            base_dir: str | Path | None = None,
        ) -> Target:
            """Embed files as Qt resources without writing .qrc XML."""
            ...

        def QtSharedLibrary(
            self,
            name: str,
            env: Env,
            sources: Sequence[str | Path | Node] | None = None,
            *,
            link: Sequence[Target] = (),
            automoc: bool = True,
            autouic: bool = True,
            autorcc: bool = True,
            no_moc: Sequence[str | Path] = (),
        ) -> Target:
            """SharedLibrary variant of QtProgram."""
            ...

        def QtStaticLibrary(
            self,
            name: str,
            env: Env,
            sources: Sequence[str | Path | Node] | None = None,
            *,
            link: Sequence[Target] = (),
            automoc: bool = True,
            autouic: bool = True,
            autorcc: bool = True,
            no_moc: Sequence[str | Path] = (),
        ) -> Target:
            """StaticLibrary variant of QtProgram."""
            ...

        def QtTranslations(
            self,
            name: str,
            env: Env,
            *,
            ts_files: Sequence[str | Path],
            prefix: str = '/i18n',
            lupdate_sources: Sequence[str | Path] = (),
        ) -> Target:
            """Compile and embed Qt translation catalogs (see module docstring)."""
            ...

        def SharedLibrary(
            self,
            name: str,
            env: Env,
            sources: Sequence[str | Path | Node | Target] | None = None,
            depends: Sequence[Target | Node | Path | str] | None = None,
        ) -> Target:
            """Create a shared library target."""
            ...

        def StaticLibrary(
            self,
            name: str,
            env: Env,
            sources: Sequence[str | Path | Node | Target] | None = None,
            depends: Sequence[Target | Node | Path | str] | None = None,
        ) -> Target:
            """Create a static library target."""
            ...

        def Tarfile(
            self,
            env: Env,
            *,
            output: str | Path,
            sources: Sequence[str | Path | FileNode | Target] | None = None,
            compression: str | None = None,
            base_dir: str | Path | None = None,
            name: str | None = None,
        ) -> ArchiveTarget:
            """Create a tar archive from source files/directories."""
            ...

        def Test(
            self,
            name: str,
            program: Target | Path | str,
            *,
            args: Sequence[str] = (),
            cwd: Path | str | None = None,
            env: dict[str, str] | None = None,
            labels: Sequence[str] = (),
            timeout: float | None = None,
            should_fail: bool = False,
            serial: bool = False,
            disabled: bool = False,
            data: Sequence[Path | str] = (),
            depends_on: Sequence[str] = (),
            discover: str | None = None,
        ) -> Target:
            """Declare a test to be run by ``pcons test`` (or ``ninja test``)."""
            ...

        def Zipfile(
            self,
            env: Env,
            *,
            output: str | Path,
            sources: Sequence[str | Path | FileNode | Target] | None = None,
            base_dir: str | Path | None = None,
            name: str | None = None,
        ) -> ArchiveTarget:
            """Create a zip archive from source files/directories."""
            ...
