/* SPDX-License-Identifier: MIT */
#include <stdint.h>

#include "blink.h"
#include "common.h"
#include "uart.h"
#include "version.h" /* generated by the host-built tool */

volatile uint32_t g_ticks;      /* .bss  */
volatile uint32_t g_state = 42; /* .data */

int main(void)
{
    static const char frame[] = "pcons";

    uart_puts("Hello from bare metal (pcons)!\n");
    uart_puts(firmware_banner());
    uart_puts("version " FW_VERSION "\n");
    uart_puts(frame_checksum((const uint8_t *)frame, sizeof(frame) - 1u) == 0x1f0fu
                  ? "checksum ok\n"
                  : "checksum bad\n");

    while (g_ticks < 4u) {
        g_ticks = blink_next(g_ticks);
        g_state ^= 1u;
    }

    uart_puts(g_state == 42u ? "state ok\n" : "state changed\n");
    semihost_exit();
    for (;;)
        ;
}
